### ISSUE TITLE
Mixin to generate objects

### ISSUE THREAD

**Issue by scottkellum** [at-import/Singularity#1]
Create a mixin to generate class based or silent objects for every position on the grid.

**Comment by Snugug** [comment]
Would the usage of this be more like this:

``` scss
.foo {
  @include sing-col(2, 3);
}

@mixin sing-col($t, $c) {
  @if $c == 3 {
    @if $t == 2 {
      @extend %col-two-three;
    }
  }
}
```
- or -

``` scss
.foo {
  @extend %col-two-three;
}
```

I prefer the first as it's a more intuitive way, especially for movers from Susy, to get the @extend in there and it doesn't require the user to guess the names (even if it's an educated guess) of generated extenders.

**Comment by scottkellum** [comment]
The first example is pretty much how the mixins behave now but they write styles, not extend objects. The second example is what this particular issue will let you do. However I will probably add something like the top feature into this as well.

I plan on writing this to work with the new extend in media query stuff. So you can write different objects to different breakpoints. Should work beautifully.

**Comment by Snugug** [comment]
Have you gotten that new extend in MQ stuff to work? When Nathan pushed it I couldn't get it to; have a working code sample?

**Comment by scottkellum** [comment]
Haven’t messed with it. In theory this should work. Will investigate when I implement this.

**Comment by Snugug** [comment]
Oh Kay

**Comment by scottkellum** [comment]
Yay building frameworks on alpha software that barely works!

**Comment by Snugug** [comment]
Yay!

We're what you call Professionals
http://www.youtube.com/watch?v=4xye0GDcV9Q

**Comment by scottkellum** [comment]
Automatically writing objects for every location on the grid done. Your choice of classes, silent selectors, or IDs if that floats your boat.

https://github.com/scottkellum/Singularity/commit/81fe2b2dedace91700a085e7e03b0cc87e6b6afe
