### ISSUE TITLE
Error when using add gutter and breakpoint slice and code kit

### ISSUE THREAD

**Issue by jcampbell05** [at-import/Singularity#100]
Here is my sass code

   $slicer-breakpoints: 0 400px 600px 800px 1050px;
   $amount-of-slices:   length($slicer-breakpoints);
   // Slice numbers:    |  1 |  2 |  3  |  4  |  5  →

   $grids: 12;
   $grids: add-grid(4 at bp(1));
   $grids: add-grid(6 at bp(2));
   $grids: add-grid(8 at bp(3));
   $grids: add-grid(10 at bp(4));
   $grids: add-grid(12 at bp(5));

   $gutters: 1/3;
   $gutters: add-gutter(.25 at bp(1));

  I keep ketting the error

error Global.scss (Line 45 of _find.scss: Undefined operation: "max-width lt 0".)
identical Global.css

**Comment by Snugug** [comment]
You shouldn't be using 0 as your first media query for your grid, the lack of media queries should be your first grid. Something like this should work, althoughI don't know Breakpoint Slicer so it very well may be a problem with that system.

``` scss
$slicer-breakpoints: 400px 600px 800px 1050px;

$grids: 4;
$grids: add-grid(6 at bp(1));
$grids: add-grid(8 at bp(3));
…

$gutters: .25;
```

The other thing to look at is whether the `bp()` function gives you the raw breakpoint value (`400px`, `600px`, etc…) or if it gives you `'min-width'`/`'max-width'`

**Comment by jcampbell05** [comment]
Okay I have got some progress, the 0px is actually the default value included with the framework.

The issue seems to spawn from the includes later on in the file if I comment it out its all fine and dandy

```
            $legacy-support-for-ie6: true;
            $legacy-support-for-ie7: true;
            $mobile-first: true;

            $body-margin: 10px;
            $font-size: 112.5;
            $line-height: 1.65;

            $slicer-breakpoints: 400px 600px 800px 1050px;
            $amount-of-slices:   length($slicer-breakpoints);
            // Slice numbers:    |  1 |  2 |  3  |  4  →

            $grids: 12;
            $grids: add-grid(4 at bp(1));
            $grids: add-grid(6 at bp(2));
            $grids: add-grid(8 at bp(3));
            $grids: add-grid(12 at bp(4));
            $grids: add-grid(12 at bp(5));

            $gutters: 1/3;
            $gutters: add-gutter(.25 at to(1));


            section > article {

                @include grid-span(9, 1);

                /*@include at(1) {
                    @include grid-span(3, 1);
                }

                @include at(2) {
                    @include grid-span(4, 1);
                }

                @include at(3) {
                    @include grid-span(6, 1);
                }

                @include at(4) {
                    @include grid-span(8, 1);
                }

                @include at(5) {
                    @include grid-span(9, 1);
                }*/

            }

            aside {

                @include grid-span(3, 9);

                @include at(1) {
                    @include grid-span(1, 1);
                }/*

                @include from(2) {
                    @include grid-span(2, 4);
                }

                @include at(3) {
                    @include grid-span(2, 6);
                }

                @include at(4) {
                    @include grid-span(2, 8);
                }

                @include from(4) {
                    @include grid-span(3, 9);
                }*/
            }

            footer {
                @include grid-span(12, 1);
            }
```

**Comment by Snugug** [comment]
Then that's improper documentation on Breakpoint Slicer's part, and sounds like a BP Slicer issue.

**Comment by jcampbell05** [comment]
Okay, do you know where the is-breakpoint-list is declared ? Breakpoint is taking what Breakpoint Slice is giving it and seems to think it is a list when its not :)

**Comment by Snugug** [comment]
`is-breakpoint-list` comes from Breakpoint. This is an issue for Breakpoint Slice, so I'm going to close this issue so you can follow up in that issue queue.
