### ISSUE TITLE
How does one add padding to an element ?

### ISSUE THREAD

**Issue by jcampbell05** [at-import/Singularity#101]
I currently have one element with text reaching the edge, I want to introduce some white space. How do I do this without destroying the Grid?

**Comment by Snugug** [comment]
If you're not already doing so,, I'd encourage you to use [`box-sizing: border-box`](http://paulirish.com/2012/box-sizing-border-box-ftw/) for all your elements. There is also an option in Singularity to turn it on for your grids only. From there, just add your padding!

**Comment by jcampbell05** [comment]
How would this effect older browsers ?

**Comment by Snugug** [comment]
Here's [Border Box in the Docs](https://github.com/Team-Sass/Singularity/wiki/Output-Options#box-sizing-border-box)
As the previously linked article states, it's fine for IE8+, with Firefox needing a `-moz` prefix and iOS<=4 and Android <=2.3 needing the `-webkit` prefix.
If you need support for <IE8, you can either install the polyfill again mentioned in the above linked article, or you can use [Toolkit](https://github.com/Team-Sass/toolkit) to both [include the box sizing change](https://github.com/Team-Sass/toolkit#border-box) and then [install the polyfill](https://github.com/Team-Sass/toolkit#odds-and-ends)

**Comment by jcampbell05** [comment]
Thank you, you've been a big help :)

The Legal Bit

This Email and any attachments contain confidential and proprietary
information of Nyx Digital Ltd and is intended for the use of the addressee
only. It may contain material protected by confidentiality provisions.
Unauthorised disclosure, copying or distribution of the Email, or its
content, may result in legal liability. If received in error please notify
the sender immediately and remove the Email and any attachments from your
computer. This Email is believed to be virus and defect free and it is the
responsibility of the recipient to ensure this, it is by no means our
intention to deliver any such nasties. Our desire is that you keep growing.
Very sorry but the sender does not accept any liability for any loss or any
damage from receipt or subsequent usage. The views and opinions expressed
in this Email are that of the individual and not of Nyx Digital Ltd and
should not be relied upon as such.
