### ISSUE TITLE
Issues with float-span in Firefox?

### ISSUE THREAD

**Issue by lmartins** [at-import/Singularity#102]
Hi,

Im having some trouble getting Firefox to behave in a particular scenario.

Im creating a simple multicolumn layout, responsive, going from single column to four columns. It works perfectly everywhere, even on IE, but Firefox both stable and Aurora shows the following:

http://cl.ly/image/2t3E3H200W0c

Apparently every column is bigger than it's supposed to, despite the rendered CSS is exactly the same as in Chrome (the screenshot shows Firefox and Chrome inspectors)

http://cl.ly/image/142L1O1B3d1r

My relevant SCSS is:

```
.solution-providers{

    @extend %box-blue2;

    article{
        @include grid-span(2,1);
    }

    @include at(2){
        article{
            @include float-span(6);
            &:nth-child(2n+1){
                @include float-span(6, "omega");
            }
        }
    }

    @include from(3){
        article{
            @include float-span(3);
            &:last-child{
                @include float-span(3, "omega");
            }
        }
    }

    h3{
        color: lighten($bc_blue2, 35%);
    }

}
```

Do you guys have any idea of what my be happening here?

**Comment by scottkellum** [comment]
I am unfamiliar with the from() and at() syntax here. Can you isolate this to an example I can compile easily?

**Comment by lmartins** [comment]
The from() and at() syntax is just a small component for Breakpoint:
https://github.com/lolmaus/breakpoint-slicer

They translate to the regular Breakpoint syntax.

Gonna try with regular syntax just to be sure that's not the root of the problem.

**Comment by lmartins** [comment]
If anyone bumps into this issue, in my case was simply related to the border-box model.
