### ISSUE TITLE
Missing !default for var $mobile-first in standard configuration?

### ISSUE THREAD

**Issue by thomasklein** [at-import/Singularity#108]
Hi!
Is the _!default_ statement missing at this point
https://github.com/Team-Sass/Singularity/blob/1.x.x/stylesheets/_singularitygs.scss#L17

or is it intentionally?

Cheers,
Thomas

**Comment by Snugug** [comment]
Resolved via bbd8b201dcdede730c9c934c2a42d64e386649f3
