### ISSUE TITLE
Mixed Static and Responsive Grid

### ISSUE THREAD

**Issue by designerbrent** [at-import/Singularity#109]
I'm wondering if there is a way to create a mixed grid as follows: 
- breakpoint 1: 3 column responsive
- breakpoint 2: 6 column responsive
- breakpoint 3: 12 column responsive
- breakpoint 4: 14 column fixed width

I'm basically attempting to limit the grid after a certain width to a static grid so it is no longer responsive.

Thanks.

**Comment by Snugug** [comment]
At breakpoint 4, set your container's width to a fixed width. Singularity does not maintain your container, it's up to you to do that
