### ISSUE TITLE
Try border instead of margin for gutters

### ISSUE THREAD

**Issue by scottkellum** [at-import/Singularity#11]
[Gridpak](http://gridpak.com/) uses borders and border-box to allow for fixed-width gutters. Look into using it in singularity.

**Comment by scottkellum** [comment]
Note this also reduces rounding errors in the browser.

**Comment by Snugug** [comment]
My only concern with this is how it works if people want to use borders as boreders.

Also, how can I help in general?

**Comment by scottkellum** [comment]
Yeah that is a concern of mine as well. Still worth looking into.

Probably not going to get to any of this until Friday. Compounding more than 2 grids needs some work if you want to take a stab at that.

Other than some testing and tweaking the docs are almost done and so is the logic. Pretty much ready for beta launch this weekend unless something big comes up. But if you have time to test and poke around that would be awesome.

**Comment by scottkellum** [comment]
Killed, too flaky when using percents and difficult to deal with background colors.
