### ISSUE TITLE
Break spans out of grid

### ISSUE THREAD

**Issue by designerbrent** [at-import/Singularity#110]
I'm wondering if there is away to break certain spans out of a grid. For example, I have a photo gallery in the middle of an article that I want to have a solid band of color all the way across the page. I can't seem to apply negative margins to it and get it do work as I would expect. 

Thanks.

**Comment by Snugug** [comment]
This is a basic HTML thing. You are either going to need to write a div wrapper and just JS to have it span the whole width, or have a div wrapper band for full color bleeds. This isn't something Singularity would handle.
