### ISSUE TITLE
Feature Request: Striping background-grid if gutters are set to 0

### ISSUE THREAD

**Issue by finteractive** [at-import/Singularity#113]
For grids with 0 gutters, please set background-grid mixin to do some kind of zebra striping on alternating grid columns.

Use-case: I'm designing grids with fluid columns & fixed gutters to allow vertical rhythm and margins to remain consistent.

**Comment by scottkellum** [comment]
Good point, will work on this at some point. Thanks!

**Comment by Snugug** [comment]
Resolved via 7b7215cb4deb7ebd4bc91aab730f0b57569fca5c

**Comment by finteractive** [comment]
Thanks - Works like a charm.
