### ISSUE TITLE
Compile error: Line 6 of _helpers.scss: "opposite" is not a list for `index'

### ISSUE THREAD

**Issue by CristinaSolana** [at-import/Singularity#114]
Hi Team Sass,

I running on Sass 3.3.0a212 with Compass 0.13a4

When attempting to use Singularity GS I am getting this error on compile:
``Line 6 of _helpers.scss: "opposite" is not a list for`index'

I tried on an existing project by requiring in config.rb and importing in scss and got this error. I tried on a fresh Singularity generated project and got the same.

I used the following vars and declaration:

$grids: 12;
$gutters: 1;

.test-grid {
    @include grid-span(3, 1);
}

Did I miss something? Any ideas?

**Comment by Snugug** [comment]
You shouldn't be able to run Compass 0.13a4 with Sass 3.3.0a212 together (they're currently incompatible). How are you compiling? Through `sass --compass`? If so, you're not getting the Ruby needed for Singularity magic to work. The code you've posted here works in the current version of Singularity being run directly through Compass.

**Comment by CristinaSolana** [comment]
Hi, thanks for the quick reply.

I wasn't running those versions before, can't remember the Sass version,
but until a few minutes ago was on Compass 0.13a0 and was having same
issue. I updated both figuring it might be an update issue.

I'm not having trouble compiling the project when I don't include the
grid-span mixin.

Using ``compass watch

**Comment by Snugug** [comment]
What version of Singularity are you running? The current version should be `1.1.1`.

Can you do me a favor? If you don't already have it installed, install [Bundler](http://bundler.io/) and do the following from your command line:

``` bash
compass create test -r singularitygs
cd test
echo "source 'https://rubygems.org' \n gem 'singularitygs', '1.1.1'" > Gemfile
bundle install
bundle exec compass watch
```

Then, open `sass/screen.scss`, delete everything there, add `@import "singularitygs";` to the file, and recompile with your example code and see if you still get the error. Using what's outlined above, I do not get the error you're getting.

What all of this is doing is that it's finding the versions of each dependency of Singularity and ensuring that the gem stack you're compiling your Sass through is compatible with Singularity and you've got all of the dependencies installed. It will also tell you if you're trying to use versions of gems that are incompatible with each other and won't let you do that.

Right now, Singularity hasn't been tested with Sass 3.3.x/Compass 0.13.x as the two are currently incompatible. Once they are, the Singularity extension will be updated to be compatible with them.

**Comment by CristinaSolana** [comment]
Hi, I am using 1.1.1. 

Using Bundler works, but it's using non-bleeding edge versions 3.2.9 and 0.12.2 of Sass and Compass, respectively - let's see if I can live with that. :P 

BTW, I can still just use `compass watch` vs `bundle exec compass watch`.

Thanks for all your help - appreciate it. :)

**Comment by Snugug** [comment]
No, need to use bundle exec. I'd set up a bash alias for it

**Comment by CristinaSolana** [comment]
Yep, thanks again for your time. :)
