### ISSUE TITLE
Asymmetrical Singularity grid with Breakpoint

### ISSUE THREAD

**Issue by designerbrent** [at-import/Singularity#115]
I've been playing with Singularity and Breakpoint and everything seems to work good till I want to create an asymmetrical grid at a breakpoint. Here is the code that works:

`$grids: add-grid(1 3 5 7 9 at 1100px);`

And this breaks: 

`$grids: add-grid(1 3 5 7 9 at $break2);`

With the following error: 
`Syntax error: List index is 6 but list is only 5 items long for `nth'
        on line 35 of /Library/Ruby/Gems/1.8/gems/singularitygs-1.0.8/stylesheets/singularitygs/math/_columns.scss, in `output-float'
        from line 4 of /Library/Ruby/Gems/1.8/gems/singularitygs-1.0.8/stylesheets/singularitygs/_api.scss, in `grid-span'...`

Am I missing something obvious or does this not work?

I'm running singularitygs (1.0.8) and breakpoint (2.0.5).

**Comment by Snugug** [comment]
Singularity 100% works with asymmetric grids and Breakpoint. This isn't enough information to debug, although from the error, it looks as if the span you're trying to make would overextend the grid you're on. (your grid is a 5 column grid, its looking for index 6)

Please provide the `grid-span` definition you're using as well.

**Comment by designerbrent** [comment]
Thanks. I find the errant grid-span by going through and commenting things out. Oops! Totally my bad!
