### ISSUE TITLE
Not possible to visualize Fixed Gutter grids

### ISSUE THREAD

**Issue by henrijs** [at-import/Singularity#116]
I'm testing Fixed Gutters and can't get grid visualization to work. It looks like Fixed Gutters work well.

**Comment by Snugug** [comment]
@henrijs Unfortunately, due to how gradients get generated (think 'content-box') and how fixed gutters work ('border-box'), it's not possible for us to generate an effective visualization, so we do alternating column colors instead.

**Comment by henrijs** [comment]
Does alternating column colors work and i am supposed to get some sort of visual alignment even with Split Gutters?

**Comment by scottkellum** [comment]
Yeah, I think altering colors is a good solution. Even though it won’t show the gutters it will at least give a general idea of the grid structure.

**Comment by Snugug** [comment]
Alternating colors for gutter width of 0/fixed grids and of split gutters for fluid gutters functions as expected. Sass Source available at [SassMeister](http://sassmeister.com/gist/6185719) and visualization of resulting background grid is available at [CodePen](http://codepen.io/Snugug/pen/CAGyj)
