### ISSUE TITLE
Can the WIKI get a sidebar?

### ISSUE THREAD

**Issue by ericduran** [at-import/Singularity#117]
Currently the wiki page (https://github.com/Team-Sass/Singularity/wiki) has a great TOC that being said it's lost as soon as you click on a link.

Can the TOC be moved to a github wiki sidebar?

kthxbye :-)

**Comment by Snugug** [comment]
I don't know what you're talking about, we've got a sidebar.

**Comment by ericduran** [comment]
@Snugug well played sir.
