### ISSUE TITLE
Website messed up on Chrome for Android

### ISSUE THREAD

**Issue by scottkellum** [at-import/Singularity#12]
z-index errors on Chrome for Android.

**Comment by scottkellum** [comment]
In iOS 5 Safari as well…

**Comment by micahgodbolt** [comment]
Takeing a quick look on android, it appears that the mobile browser doesn't handle fixed elements quite the same as desktop. The horrible, but easy answer would be converting that cool html element to a background image. I'll poke at it a bit more when I get a little time.

**Comment by scottkellum** [comment]
may just ignore and focus on a new site.
