### ISSUE TITLE
Singularity + Toolkit invokes deprecated use of @extend

### ISSUE THREAD

**Issue by rupl** [at-import/Singularity#120]
Got a minor-but-scary warning as I set up the most basic grid in Singularity:

```
>>> Change detected at 21:03:29 to: design/_block-second-nav.scss
DEPRECATION WARNING on line 14 of /var/lib/gems/1.8/gems/toolkit-1.3.5/stylesheets/toolkit/_box-sizing.scss:
  @extending an outer selector from within @media is deprecated.
  You may only @extend selectors within the same directive.
  This will be an error in Sass 3.3.
  It can only work once @extend is supported natively in the browser.
```

The warning was output twice for each `grid-span()`

I was able to rid myself of the warning by removing `@import 'toolkit';` and including border-box manually. The partial structure is aurora/corona for the most part.

The code that caused the warning (from various files but you get the idea):

```
$mobile-first         : true;
$include-border-box   : true;
$include-clearfix     : false;

$grids                : 12;
$gutters              : 1/3;

$breakpoint-no-query-fallbacks: true;
$breakpoint-to-ems: true;

$columns: 800px;

.panel-twocol {
  .panel-sidebar {
    padding: 0 1em;
    @include breakpoint($columns) {
      @include grid-span(4,1);
    }
  }
  .panel-content {
    padding: 0 1em;
    @include breakpoint($columns) {
      @include grid-span(8,5);
    }
  }
}
```

**Comment by Snugug** [comment]
I know the cause and I'll work on a solution

**Comment by rupl** [comment]
After hitting submit I realized a simpler solution is to leave toolkit and ~~comment out~~ set this to false `$include-border-box   : true;`

**Comment by Snugug** [comment]
Yup. If you have border-box on everything already, don't need it.

**Comment by Snugug** [comment]
Setting `include border box` to false will stop this, but there's a larger issue with Toolkit automatically assuming extends. A future update to Toolkit is needed to even out its logic.
