### ISSUE TITLE
Create and maintain a changelog

### ISSUE THREAD

**Issue by scottkellum** [at-import/Singularity#126]
Good example: https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.rdoc

**Comment by Snugug** [comment]
+1. Been meaning to do this whenever I push new changes. Now it's a thing!

**Comment by scottkellum** [comment]
Ruby devs at my work scolded me for this.

**Comment by Snugug** [comment]
Resolved in #157  (which will become v1.2.0 of Singularity)
