### ISSUE TITLE
Syntax error: "opposite" is not a list for `index'

### ISSUE THREAD

**Issue by dotherightthing** [at-import/Singularity#127]
Hi,

I've just set up Singularity so I can do a comparison with Susy on a new project I'm starting today.

Compass is giving me the following errors:

```
Syntax error: "opposite" is not a list for `index'
on line 6 of /Users/Dan/.rvm/gems/ruby-1.9.3-p194/gems/singularitygs-1.1.2/stylesheets/singularitygs/gutter-styles/_helpers.scss,
in `background-build' from line 136 of /Users/Dan/.rvm/gems/ruby-1.9.3-p194/gems/singularitygs-1.1.2/stylesheets/singularitygs/helpers/_background-grid.scss,
in `background-grid' from line 21 of /Users/Dan/Websites/project/htdocs/resources/styles/sass/_grid_singularity.scss
from line 5 of /Users/Dan/Websites/project/htdocs/resources/styles/sass/screen_singularity.scss
1: /Users/Dan/Websites/project/htdocs/resources/styles/sass/screen_singularity.scss
```

My scss so far is pretty minimal..

```
//_grid_singularity.scss
@import "singularitygs";

$grids: 2 8 2;
$gutters: 1/3;

.sg-container {
    @include background-grid;
    max-width: 940px;
}
```

Versions:

```
*** LOCAL GEMS ***
bigdecimal (1.1.0)
breakpoint (2.0.6)
chunky_png (1.2.8)
compass (0.13.alpha.4)
fssm (0.2.10)
io-console (0.3)
json (1.5.4)
listen (0.7.3)
minitest (2.5.1)
rake (0.9.2.2)
rdoc (3.9.4)
sass (3.2.10)
singularitygs (1.1.2)
```

Thanks,  
Dan

**Comment by scottkellum** [comment]
I can’t seem to replicate in a quick test here: http://sassmeister.com/gist/6228112

**Comment by Snugug** [comment]
I, likewise, am unable to to reproduce this while under [Bundler](http://bundler.io/) control for Singularity 1.1.2. Are you using Bundler for gem version control? If not, can you please try putting your stack under Bundler control. The Gemfile I tested with is simply:

```
gem 'singularitygs', '1.1.2'
```

**Comment by dotherightthing** [comment]
Thanks guys, I've installed Bundler and used the suggested Gemfile content and am up and running now :)

Out of curiosity, there's a Gemfile in the root of your Github repo, but the syntax seems slightly different to what is shown on the Bundler site. Should I be able to point Bundler at that file, or does it have another purpose?

Thanks,
Dan

**Comment by scottkellum** [comment]
@dotherightthing A gemfile is usually project-specific based on your unique projects needs. You should manage your own gemfile independently and add other Compass plugins you use to it.
