### ISSUE TITLE
Fixed Width Gutter bug

### ISSUE THREAD

**Issue by starryeyez024** [at-import/Singularity#128]
I'm seeing a serious bug with fixed width gutters. 

I built a brand new Drupal 7 install with the latest recommended release version of Omega 4 with a brand new layout. (I was also trying it with another theme previously so Omega is not the issue). I tore out 90% of the Sass, and commented out lines one by one til I deduced that the gutters were the problem. 

Here is a screenshot of my code and my site with no gutter variables specified. 
http://note.io/16fngNg

Here is a screenshot of my code and my site with a 10px fixed gutter.
http://note.io/14OiI3o 

Here is the same site with the $gutters: 10px at the mobile view 
http://note.io/14Oj9KZ

If I try to use $gutter-styles: 'split' 'fixed' I get this error:
error sass/layouts/twc/twc.layout.sass (Line 15: Invalid CSS after "'split' fixed": expected expression (e.g. 1px, bold), was "'")

**_Also here is a list of all my local gems and the version number**_
actionpack (3.2.13)
activemodel (3.2.13)
activesupport (3.2.13)
addressable (2.3.4, 2.3.3)
bigdecimal (1.2.0)
bourbon-compass (3.1.8)
breakpoint (2.0.5, 1.3)
builder (3.0.4)
bundler (1.3.5)
bundler-unload (1.0.1)
chunky_png (1.2.8, 1.2.7)
coderay (1.0.9)
color-schemer (0.2.5)
compass (0.12.2)
compass-blend-modes (0.0.2)
compass-normalize (1.4.3)
compass-rgbapng (0.2.0, 0.1.1)
compass-validator (3.0.1)
css_parser (1.3.4)
em-websocket (0.5.0)
erubis (2.7.0)
eventmachine (1.0.3)
ffi (1.9.0, 1.4.0)
formatador (0.2.4)
fssm (0.2.10)
guard (1.7.0, 1.6.2)
guard-compass (0.0.6)
guard-livereload (1.3.0, 1.1.3)
guard-shell (0.5.1)
hike (1.2.3)
http_parser.rb (0.5.3)
i18n (0.6.1)
io-console (0.4.2)
journey (1.0.4)
jquery-rails (1.0.19)
json (1.8.0, 1.7.7)
listen (0.7.3)
lumberjack (1.0.3)
method_source (0.8.1)
minitest (4.3.2)
modular-scale (1.0.6)
multi_json (1.7.7, 1.7.1)
oily_png (1.1.0)
pry (0.9.12.2, 0.9.12)
psych (2.0.0)
rack (1.4.5)
rack-cache (1.2)
rack-ssl (1.3.3)
rack-test (0.6.2)
railties (3.2.13)
rake (10.0.4, 0.9.6)
rb-fchange (0.0.6)
rb-fsevent (0.9.3)
rb-inotify (0.9.1, 0.8.8)
rdoc (4.0.0, 3.12.2)
redis (2.2.2)
redis-native_hash (0.2.2)
respond-to (2.6)
rubygems-bundler (1.2.0)
rubygems-update (2.0.6)
rvm (1.11.3.8)
sass (3.2.9, 3.2.7)
sass-globbing (1.1.0, 1.0.0)
sass-media_query_combiner (0.0.2)
sassy-math (1.5)
sassy-strings (0.3.1)
singularity (0.0.2)
singularitygs (1.1.2, 1.0.8, 0.0.17)
slop (3.4.5, 3.4.4)
sprockets (2.2.2)
susy (1.0.8, 1.0.7)
terminal-table (1.4.5)
test-unit (2.0.0.0)
thor (0.18.1, 0.17.0)
tilt (1.4.1)
toolkit (1.1.1, 0.2.6)
yajl-ruby (1.1.0)
zurb-foundation (4.2.3)

**Comment by Snugug** [comment]
Please provide a SassMeister example so I can see both your input Sass and your output CSS in a version controlled environment. Please also make sure you're running your Compass compile through Bundler (`bundlr exec`) and not just `compass watch`

**Comment by starryeyez024** [comment]
Code: https://gist.github.com/starryeyez024/6245996
I just ran it with bundle exec compass watch and it didnt throw any errors, but my grid looks the same. 
Thanks for looking it over.

**Comment by Snugug** [comment]
I'll take a look

**Comment by Snugug** [comment]
Are you using `.sass` syntax or `.scss` syntax? The gist you've provided appears to be `.sass` syntax while the comment says it's a `.scss` file. What is the output you're expecting? Running this in [SassMeister](http://sassmeister.com/gist/6246030) produces the expected output (remove the top comment, SassMeister generation bug). You can change `$gutter-styles` to `'split' 'fixed'` as well and it works. Please keep in mind that the visualizations aren't exact; it's much more accurate to create actual grid items and use them for grid visualization.

**Comment by starryeyez024** [comment]
sorry for the confusion, it is a .sass file, i converted a file from .scss to .sass from the Omega theme, hence the comment at the top. The output I'm expecting should look like http://note.io/16fngNg - but as I scale the window the gutters should remain fixed at 10px instead of expanding with the gutters. 
I also just updated Sass to 3.2.10, but that didn't have an effect.  My generated CSS is different than what sassmeister is generating and I don't know why. http://note.io/1eNSixE

**Comment by Snugug** [comment]
Screenshots help less than input Sass/output CSS. Can you please remove all code from your codebase except for the code you've supplied in [your previous comment](https://gist.github.com/starryeyez024/6245996) and the output CSS you get from it, running it from Bundler. Can you please also provide your full Gemfile and ensure you're running your compass compile with `bundle exec`. Please also clean your compass cache by running `compass clean`.

**Comment by scottkellum** [comment]
From what I have reverse engineered from your source I am not seeing what you are seeing: http://codepen.io/scottkellum/pen/fac1abf0cfc021954ce108066bc28ade

**Comment by starryeyez024** [comment]
Sorry for the delay. Here is a git repo with the sass I'm using and a demo html file. (They are named omega-demo but that's irrelevant).
https://github.com/starryeyez024/singularity-gutters

Also here is a screenshot of the HTML file rendered in the browser: http://note.io/16dQSaq

**Comment by Snugug** [comment]
Taking a look at your Gemfile and your Gemfile.lock, I've found your issue.

You aren't defining any gem versions in your Gemfile, meaning that you're not actually tracking your version dependencies. While you've got Singularity 1.1.2 installed locally, diving in to your your actual lock file, [you are using Singularity 1.0.8](https://github.com/starryeyez024/singularity-gutters/blob/master/Gemfile.lock#L70). Because fixed gutters weren't introduced until 1.1.0, you're trying to use a feature that doesn't exist in the version you're locked to. Doing this and running `bundle exec compass compile` compiles with fixed gutters with no issue.

To solve this issue, do the following:

1.Run `bundle update` and you'll be updated to the newest version of Singularity (as well as your other gems). 
2. Include version numbers in your Gemfile, and only include the gems you are actually using in your project (for instance, don't include both Susy and Singularity in you Gemfile). Take a look at [Aurora's Gemfile](https://github.com/Snugug/Aurora/blob/master/templates/shared/Gemfile.txt). Also look at [Bundler's Documentation](http://bundler.io/v1.3/gemfile.html) for how to write a Gemfile.

**Comment by starryeyez024** [comment]
Thank you, that worked! Apologies, my system gems including singularity are up to date. That gemfile.lock came from an existing Omega 4.x subtheme in Drupal.
Originally I wasn't using gemfiles, but I think that was before I updated my system gems. Thanks again for helping me sort this out. :)
