### ISSUE TITLE
Fix background-grid color variable name in "Creating Grids: Visualizing Grids" Wiki page

### ISSUE THREAD

**Issue by cfarm** [at-import/Singularity#129]
The background-grid arguments section is not the most clear. It appears to have the wrong variable name for the color argument (it's $color not $background-grid-color) and has no code example. I made an example on my forked Wiki here:

https://github.com/cfarm/Singularity/wiki/Creating-Grids

**Comment by Snugug** [comment]
Resolved: https://github.com/Team-Sass/Singularity/wiki/Creating-Grids#visualizing-your-grids
