### ISSUE TITLE
recursive contexts

### ISSUE THREAD

**Issue by codingdesigner** [at-import/Singularity#13]
I'm diving into this and gridset this week, and the feature both are lacking (or maybe I'm missing it) is what I'm calling recursive contexts. I've got a layout with a main content section, and a sidebar section. I want to subdivide the main section and align nested elements in there to an overall grid. This is done in even grids like susy by setting the 'context' of the nested elements. I think singularity needs that concept as well. 

[Here's an illustration for clarity. ](https://skitch.com/e-canarymason/e8skm/gridset-cheat-wef)

**Comment by scottkellum** [comment]
This is what the gutter-context function is for: https://github.com/scottkellum/Singularity/blob/master/stylesheets/singularitygs/_helpers.sass#L20-21

Not sure how you are generating column styles with singularity, but you would use this in place of the gutter variable.

defaults (overall grid):

``` sass
$columns: 1, 2, 3, 4
$gutter: 2%
```

Your vars for your nested grid spanning cols 1-3 would look like this:

``` sass
$gutter: gutter-context(2%, grid-span(3, 1))
$columns: 1, 2, 3
```

Probably a way to simplify that, but it creates a two percent gutter for the context of the first three columns.

**Comment by codingdesigner** [comment]
digging deeper. This is working for me. I'm going to use this in a real project and contrib stuff along the way. this design has to support rtl layouts, so I'm sure I'll have to address that along the way.

**Comment by scottkellum** [comment]
Awesome, yeah haven’t dug into rtl yet. Logic is pretty modular so might not be an issue to write the grid rtl, but lots of parts like lists you might want to flip as well. But you might not want to flip those because CSS is ltr.
