### ISSUE TITLE
Opposite is not a list for index

### ISSUE THREAD

**Issue by aprice42** [at-import/Singularity#132]
Hello, I am running into an intermittent issue where I am getting the on-screen warning: 

Syntax error: "opposite" is not a list for `index'
on line 6 of /Library/Ruby/Gems/1.8/gems/singularity-1.1.2/stylesheets/singularitygs/gutter-styles/helpers.scss, in`output-isolation'
from line 7 of  /Library/Ruby/Gems/1.8/gems/singularity-1.1.2/stylesheets/singularitygs/_api.scss, in `grid-span'
from line 32 of /Users/andyprice/Sites/ns.dev/docroot/sites/all/themes/ns_responsive/sass/layout.scss

The issue seems to  be triggered whenever I make a change to one of my sass files that results in a parsing error, once I fix the error, if I refresh the page, the above error message will persist until I comment out all "@include grid-span()" declarations and re-compile css. Once the page is loading properly again with all grid-spans commented out, I can then uncomment all of the @include grid-span() declarations re-compile and I will be up and running again with the grid-spans working as expected. 

I am using 
singularity 1.1.2
compass 0.12.2 (Alnilam)
and I am using "compass watch" to compile css

Any advice as to what is going on would be greatly appreciated!

Thanks,
Andy

**Comment by Snugug** [comment]
Can you please provide some code for us to help debug this? This error message is too vague for us to work on
