### ISSUE TITLE
add-grid returns "Undefined operation"

### ISSUE THREAD

**Issue by ghost** [at-import/Singularity#138]
Hi

If I write

$grids: 1;
$grids: add-grid(1 at 960px);
$gutters: 1/2

then it returns an error like:

Syntax error: Undefined operation: "1/110.5 times 100%".
on line 44 of ... /_columns.scss, in 'background-build'
from ... and so on.

**Comment by martindines** [comment]
How odd; I can't seem to reproduce this either.

What version of Singularity are you using?
Can you paste the contents of L44 @ _columns.scss

**Comment by flatsteve** [comment]
I'm experiencing the same error: Singularity works fine with one grid but when I try to add a new grid it returns operation undefined. 

I'm running Compass 0.13alpha.10 and Sass 3.3.0.rc.1.

I saw Scott comment on another issue stating there was know issues with this configuration. Is that the issue?

Cheers guys - really love this grid system.

**Comment by lolmaus** [comment]
This is a known issue. Singularity is not yet compliant with Sass 3.3. You should wait for a new (pre)release. Maybe there's already some dev branch on Github.

**Comment by flatsteve** [comment]
@lolmaus Thanks very much for clarification! I'll have a look around.

**Comment by Snugug** [comment]
Yah, this is a known issue as Singularity isn't compatible with Sass 3.3 yet.
Resolved in #157  (which will become v1.2.0 of Singularity)
