### ISSUE TITLE
Issues with singularitygs and breakpoint using compass.app on Windows 8

### ISSUE THREAD

**Issue by doostinharrell** [at-import/Singularity#141]
When generating css files I receive the following error message:

error sass/grassroots.styles.scss (Line 66 of _context.scss: Invalid CSS after "...holder, comma) ": expected "}", was "!global;")

This file is related to the _context.scss file for the breakpoint extension.

**Comment by Snugug** [comment]
Yup, it would. Breakpoint is a Compass extension and requires a bit of Ruby, so you cannot use the straight Sass files until we update everything until Sass 3.3, but then it will only work with compilers compatible with Sass 3.3

**Comment by doostinharrell** [comment]
Gotcha.  It seems like everything works fine running compass on my Linux box just not via compass.app in Windows.  Ruby however is pounding the CPU on my Linux box ... I don't like waiting 15 seconds for livereload to fire :(.  Guess I will deal until sass 3.3 is released.

Thanks you for your help snugug.
