### ISSUE TITLE
License quibble -- need license text files

### ISSUE THREAD

**Issue by JeNeSuisPasDave** [at-import/Singularity#150]
The Readme says the license is dual MIT/GPL. But that means little. Without a license file or files in the distribution, the software is effectively just copyrighted and no one is licensed to use it.

The Ruby spec for specify a license (http://guides.rubygems.org/specification-reference/#licenses=) says: "The license must be a short name, no more than 64 characters. This should just be the name of your license. The full text of the license should be inside of the gem when you build it. See http://opensource.org/licenses/alphabetical for a list of licenses and their abbreviations (or short names)."

The gemspec currently specs the licenses as: s.licenses = ["MIT", "GPL"]
Although the name "MIT" is mapped to a license at opensource.org, the name "GPL" is not mapped and is ambigous. It could mean LGPL-2.1 or GPL-3.0 or perhaps some early variant of GPL.

Why am I nit-picking? Because the lawyers who review the licenses of packages I want to use will not approve use of Singularity. They will run screaming from the "GPL" and from the lack of actual license text in actual files in the actual distribution.

What is needed is an unambigous declaration of the licenses, inclusion of the license text, and a clear definition of what "dual license means" (I would like to assume it means I can apply the terms of the MIT license and ignore the GPL terms; but I have no way of knowing that's what Team-Sass meant.)

**Comment by Snugug** [comment]
Thanks for the heads up. We will add licenses in for MIT and GPL-3.0 (the version of GPL we have licensed it under) in the next release. Until then, the way our dual license works means that you can choose to either apply the terms of MIT or GPL-3.0 when you use Singularity.
