### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by starryeyez024** [at-import/Singularity#151]
First, thank you! SIngularity GS rocks! I just read through the documentation and have some suggested improvements. 

The [Find Functions](https://github.com/Team-Sass/Singularity/wiki/Grid-Helpers#find-functions) section could really use examples of how to utilize the find-grid functions. There is no mention of adding @debug find-grid(); in your sass file, and then looking in terminal to see the number of columns that item spanned; so I struggled for a while trying to understand how to use this tool.

The demo code created with

```
bundle exec compass create {project name} -r singularitygs --using singularitygs
```

generates .scss which includes push & pull functions, but these are not mentioned anywhere in the documentation. I think there is a bug involving the pull functions not accounting for gutters properly (they seem [offset](http://note.io/1cNmGrO) even in the untouched float demo sass), but I'll file a separate issue for that. 

Typos: under the clearfix mixin section it says, "ThecClearfix".

I think it would be useful to link to the actual [grid-span function](https://github.com/Team-Sass/Singularity/wiki/Grid-Helpers#grid-span) from the [Grid Span](https://github.com/Team-Sass/Singularity/wiki/Spanning-The-Grid#grid-span) section of the documentation to help people understand it better.

I also would love to see an explanation on how to deal with gutters on the edge of your grid. I've had some mixed results with the demo code even where some divs line up with the edges, and others stick out. Sometimes my grids have extra space along the right edge, and sometimes they don't. Even just some example code would be helpful!

Lastly this could have been done for simplicity's sake or perhaps I don't understand it all the way, but when reading the [Group Context Overrides" example](https://github.com/Team-Sass/Singularity/wiki/Spanning-The-Grid#group-context-overrides), I wasn't sure how or why it made sense to use the layout span in the way that is shown. Surely you use group context overrides in conjunction with breakpoints? But that is not shown in the example, which I think is actually pretty important to drive them point home in why you might use it at all. 

```
$grids: 12;
$gutters: 1/3;

#foo {
  // Grid context: 12
  // Gutter context: 1/3
  // Output Style: Isolation
  @include grid-span(3, 1);

  @include layout(2 8 2) {
    @include breakpoint($tablet) {      
      // Grid context: 2 8 2
      // Gutter context: 1/3
      // Output Style: Isolation
      @include grid-span(1, 1);
    }
    @include breakpoint($desktop) {      
      // Grid context: 2 8 2
      // Gutter context: 1/3
      // Output Style: Isolation
      @include grid-span(2, 1);
    }
  }
}
```

**Comment by Snugug** [comment]
Are these documentation concerns still valid with Singularity 1.2.x?

**Comment by Snugug** [comment]
Seeing no movement, closing.
