### ISSUE TITLE
Could not install singularitygs in Windows ?

### ISSUE THREAD

**Issue by abijith** [at-import/Singularity#152]
Could not install singularitygs now on Windows with the command " gem install singularitygs" in Ruby200 folder using command promt. Getting an error as below.

C:\Ruby200>gem install singularitygs
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: compass requires compass-core (~> 1.0.0.alph
a.13), listen (~> 1.1.0); sass requires listen (~> 1.1.0)

Kindly help me and provide assistance to have this installed on our system.

Thanks!
Abi

**Comment by Snugug** [comment]
As documented in the the [installation instructions](https://github.com/Team-Sass/Singularity/wiki/Installation#installation), installation of Singularity should be done through Bundler, which manages the fetching and installing of dependencies.

**Comment by abijith** [comment]
Thank you for replying. I have installed bundler through command prompt, however could not install the sass and other as per the installation instructions.

Please see the below image to see the error. Kindly help!

![image](https://f.cloud.github.com/assets/1226023/1665059/2078dfc4-5c31-11e3-9941-9bcd76ba3dcb.png)

**Comment by Snugug** [comment]
Please read the [Bundler documentation on Gemfiles](http://bundler.io/v1.5/gemfile.html) and reread the [installation instructions](https://github.com/Team-Sass/Singularity/wiki/Installation#installation)

**Comment by abijith** [comment]
Getting the same error. Please let me know what i am doing wrong. Please see the screenshot below.

![image](https://f.cloud.github.com/assets/1226023/1665150/8a0149c6-5c32-11e3-8478-c20dddddc266.png)

**Comment by Snugug** [comment]
Please reread the Gemfile instructions. You need to create a Gemfile and put the content from the installation instructions into the gem file, then run bundle install. Also read [Heroku instructions on Bundler](https://devcenter.heroku.com/articles/bundler) to get an idea of how Bundler works as well

**Comment by abijith** [comment]
Thank you so much for you help! I have created a gem file and this is fixed now.
