### ISSUE TITLE
Singularity development is now offically stopped as it is rolled into Susy Next.

### ISSUE THREAD

**Issue by antonkulaga** [at-import/Singularity#154]
On master's branch I see that "Singularity development is now offically stopped as it is rolled into Susy Next." in the same time I see fresh commits to 1.x.x branch. Could you explain me should I switch to Susy.Next or you changed your mind and decided to develop singularity.gs separately from Susy.Next and simly forgot to delete announcement about Susy from master branch?

**Comment by Snugug** [comment]
As you can see from the README and contributing docs, Singularity is alive and well. Master is very old and should be deleted. We are committed to Singularity development

**Comment by antonkulaga** [comment]
Thank you for clarification as I was confused by the announcement on master, maybe you should delete old master and than rename 1.x.x branch to master as people prefer to think of master branch as of main branch?

**Comment by Snugug** [comment]
We will consider deleting master but we will probably continue having version branches
