### ISSUE TITLE
Error on Singularity install on Sass 3.2.13 and Compass 0.12.2 - Sassy Maps requires Sass 3.3 rc

### ISSUE THREAD

**Issue by rpkoller** [at-import/Singularity#158]
I am running Sass 3.2.13 and Compass 0.12.2 on OSX 10.8.5. with Ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0] and Gem 1.3.6 . I had a few gem issues especially with Modular Scale. finally lead to a striped down and simple gem set up preceded with a clean install: 

```
*** LOCAL GEMS ***

breakpoint (2.0.7)
chunky_png (1.2.9)
compass (0.12.2)
fssm (0.2.10)
modular-scale (2.0.0.alpha4)
sass (3.2.13)
```

@scottkellum already helped me over at the modular scale repo to figure things out. One of the only two remaining gems i need is Singularity. I wanted to install the latest version of Singularity able to run with stable Sass and Compass, like i did with Breakpoint 2.0.7, until the new Sass and Compass versions go final . Unfortunately no matter which version i try to install: 

```
sudo gem install singularitygs -v 1.x.x
```

i get:

```
ERROR:  Error installing singularitygs:
    sassy-maps requires sass (~> 3.3.0.rc.2, runtime)
```

Odd part is if i try for example

```
sudo gem install singularitygs
```

I get the aformentioned error too but my local gem list looks like that afterwards: 

```
*** LOCAL GEMS ***

breakpoint (2.0.7)
chunky_png (1.2.9)
compass (0.12.2)
fssm (0.2.10)
modular-scale (2.0.0.alpha4)
sass (3.2.13)
singularitygs (1.1.2)
```

And the gem is working properly in test cases. Just wanted to inform the rest of the mainters over here like Scott wanted me to do. Best regards Ralf

**Comment by Snugug** [comment]
As described in our [Installation Instructions](https://github.com/Team-Sass/Singularity/wiki/Installation#installation), you should be installing/using Singularity through Bundler to ensure the correct versions of each gem are being used. Modular Scale, for instance, is the new alpha version for Sass 3.3, which Singularity 1.1.2 doesn't support.

Install and try to run through Bundler.
