### ISSUE TITLE
browser support warning on compass compile

### ISSUE THREAD

**Issue by csrow** [at-import/Singularity#160]
I am getting a warning message from compass-core _support.scss file (line379) about $legacy-support-for variables no longer being supported.

It traces back to singularitygs _box_sizing.scss which imports compass/css3/_deprecated-support.scss.

Is this an issue with Compass or with Singularitygs?  Anyway to fix?

Thank you.

**Comment by Snugug** [comment]
As described in the [Singularity Requirements](https://github.com/Team-Sass/Singularity/wiki/Installation#requirements), Singularity 1.1.x is not compatible with Compass 1.0.x or Sass 3.3.x. We are working on an update to Singularity to make it compatible with the newest versions of Sass and Compass, but until then you need to use latest stable releases, not the prereleases. Use [Bundler](https://github.com/Team-Sass/Singularity/wiki/Installation#installation) to ensure you're using the correct Sass and Compass versions.
