### ISSUE TITLE
Was the sass str-index function renamed? I get an error!

### ISSUE THREAD

**Issue by axe312ger** [at-import/Singularity#164]
My css is no more generated. I get an error from singularitygs code. It seems, that the sass developers renamed or removed the str-index function!

```
on line 71 of [...]bundler/gems/Singularity-ca30faaf10e1/stylesheets/singularitygs/helpers/_settings.scss, in `add-gutter-style'
```

**My Gemfile:**
gem 'sass', :git => 'git://github.com/nex3/sass.git', :branch => 'master'
gem 'compass', :git => 'git://github.com/chriseppstein/compass.git', :branch => 'master'
gem 'singularitygs', :git => 'git://github.com/Team-Sass/Singularity.git', :branch => '1.x.x'
gem 'breakpoint', '>=2.4.1'

**Comment by lolmaus** [comment]
Probably related to this: https://github.com/nex3/sass/issues/1112

**Comment by Snugug** [comment]
In Sass 3.3.rc.3, they changed what `str-index` returns if it doesn't find anything (previously, `-1`, now `null`). Singularity will be updated soon.

**Comment by axe312ger** [comment]
This is fixed as far as i can see :)
