### ISSUE TITLE
libsass

### ISSUE THREAD

**Issue by iwyg** [at-import/Singularity#165]
is it somehow possible to use singularity with libsass instead of ruby/sass?

Thanks

**Comment by Snugug** [comment]
Singularity 1.2.x and above will be compatible with any Sass compiler with Sass 3.3.0 compatibility. Once libsass  has that compatibility, it will work fine with it. At the moment, libsass's compatibility is roughly equal to Sass 3.1.0. Singularity 1.1.x and below requires Ruby.
To track libsass compatibility, please refer to [libsass/282](https://github.com/hcatlin/libsass/issues/282)

**Comment by iwyg** [comment]
Thanks
