### ISSUE TITLE
Asymmetric grid prevents Codekit from compiling

### ISSUE THREAD

**Issue by david-silva** [at-import/Singularity#166]
When trying to declare an Asymmetric grid ($grids: 2 8 2; $gutters: 1/3;) Codekit returns the error message below. It works fine with Symmetric grids.

What can I do?

WARNING: The compass/css3/shared module has been deprecated.
You can silence this warning by importing compass/css3/deprecated-support instead.
Please be aware that module will be removed in the next release.
         on line 1 of /Library/Ruby/Gems/2.0.0/gems/compass-core-1.0.0.alpha.17/stylesheets/compass/css3/_shared.scss
         from line 1 of /Library/Ruby/Gems/2.0.0/gems/singularitygs-1.1.2/stylesheets/singularitygs/helpers/_box-sizing.scss
         from line 8 of /Library/Ruby/Gems/2.0.0/gems/singularitygs-1.1.2/stylesheets/singularitygs/_helpers.scss
         from line 36 of /Library/Ruby/Gems/2.0.0/gems/singularitygs-1.1.2/stylesheets/_singularitygs.scss

**Comment by Snugug** [comment]
Singularity 1.1.x doesn't work with Compass 1.1.0, you need to upgrade to Singularity 1.2.x. If you are not using Bundler to manage your gem dependencies ([which we recommend](https://github.com/Team-Sass/Singularity/wiki/Installation#wiki-installation)), run `gem install singularitygs --pre` to install 1.2.x

**Comment by david-silva** [comment]
I made the update to 1.2 and the background grid include stopped working? It's also not recognizing the variables declared- it sticks to the 12 column default. Although I seem to be able to change the context just fine when spanning the grid.

**Comment by Snugug** [comment]
There were a handful of unavoidable changes made to grid declaration. Please read the CHANGELOG to view the updates until we update our docs.

**Comment by alanmoo** [comment]
To get the background grid, turn on debug mode. `@include sgs-change('debug', true);`
(This wasn't in the changelog, I stumbled across it in the examples.)

I'm actually not able to get asymmetric grids to compile either, using Singularity v1.2.0.rc.6, installed via Bower. Should I create another ticket?

**Comment by david-silva** [comment]
Thanks for the help so far. Looks like I've got most things working as needed. 

Where should the debug include be placed?

**Comment by alanmoo** [comment]
Outside of any selectors. (Probably at the top of your Sass file, after Singularity is included.)
