### ISSUE TITLE
Incompatible units: 'em' and '%'

### ISSUE THREAD

**Issue by Timoti** [at-import/Singularity#167]
Oh pants! I love the idea of singularity but it's always been the framework that breaks my drupal theme compile

```
>>> Change detected to: /Users/Shared/Documents/design-projects/-x-project-dev/drupal-7-bikeeastbay/sites/default/themes/bike_east_bay/sass/layouts/homeblocked-resp-off-canvas/_homeblocked-resp-off-canvas.scss

error /Users/tim/.rvm/gems/ruby-1.9.3-p484/gems/singularitygs-1.1.2/stylesheets/singularitygs/api/_float.scss (Line 139: Incompatible units: 'em' and '%'.)
```

FWIW, this is for a Drupal Omega 4 subtheme. Its GEMFILE reads:

```
source 'https://rubygems.org'

group :development do

  # Sass, Compass and extensions.
  gem 'sass'                    # Sass.
  gem 'sass-globbing'           # Import Sass files based on globbing pattern.
  gem 'compass'                 # Framework built on Sass.
  gem 'compass-validator'       # So you can `compass validate`.
  gem 'compass-normalize'       # Compass version of normalize.css.
  gem 'compass-rgbapng'         # Turns rgba() into .png's for backwards compatibility.
  gem 'susy'                    # Susy grid framework.
  gem 'singularitygs'           # Alternative to the Susy grid framework.
  gem 'toolkit'                 # Compass utility from the fabulous Snugug.
  gem 'breakpoint'              # Manages CSS media queries.
  gem 'oily_png'                # Faster Compass sprite generation.
  gem 'css_parser'              # Helps `compass stats` output statistics.

  # Guard
  gem 'guard'                   # Guard event handler.
  gem 'guard-compass'           # Compile on sass/scss change.
  gem 'guard-shell'             # Run shell commands.
  gem 'guard-livereload'        # Browser reload.
  gem 'yajl-ruby'               # Faster JSON with LiveReload in the browser.

  # Dependency to prevent polling. Setup for multiple OS environments.
  # Optionally remove the lines not specific to your OS.
  # https://github.com/guard/guard#efficient-filesystem-handling
  gem 'rb-inotify', '~> 0.9', :require => false      # Linux
  gem 'rb-fsevent', :require => false                # Mac OSX
  gem 'rb-fchange', :require => false                # Windows
```

I'm not at all a ruby guy but have had some ruby gurus set up my rvm and bundler on OS 10.9 Mavericks.

Any ASAP ideas on this will be gratefully received

Tim

**Comment by Snugug** [comment]
What do your grid definitions look like?

**Comment by Timoti** [comment]
hi - cheers

as below
but note that error happens without all of that code (edited down for this post) 
except the partials imports

@import "partials/utility";
@import "partials/base";

// LAYOUT
// /////////////////////////////////////////

@include breakpoint($tab) {

// SIDEBARS
.two-sidebars,
.one-sidebar {
  .l-content {
    @include grid-span(8, 1);
  }
  .l-region--sidebar-first,
  .l-region--sidebar-second {
    @include grid-span(4, 9);
    clear: right;
    }
  }
}

@include breakpoint($desk) {

.l-constrained {
  width: 80%;
  }

// SIDEBARS
.one-sidebar {
  .l-content {
    @include grid-span(8, 1);
    }
  .l-region--sidebar-first {
    @include grid-span(4, 9);
    clear: none;
      }
    }
.two-sidebars {
  .l-content {
    @include grid-span(6, 1);
    }
  .l-region--sidebar-first,
  .l-region--sidebar-second {
    @include grid-span(3, 7);
    clear: none;
    }
  .l-region--sidebar-second {
    @include grid-span(3, 10);
    }  
  }

}

//  HOME BLOCKS
@include breakpoint($desk) {
.block.home-block {
overflow: auto;
:nth-child(1) {
    @include grid-span(4, 1);
    }  
:nth-child(2) {
    @include grid-span(4, 5);
    }
:nth-child(3) {
    @include grid-span(4, 9);
    clear:right;
    }  
:nth-child(4) {
    @include grid-span(4, 1);
    }
:nth-child(5) {
    @include grid-span(4, 5);
    }
:nth-child(6) {
    @include grid-span(4, 9);
    }
  }
}

**Comment by lolmaus** [comment]
Can you share a minimal failing case via http://sassmeister.com ?

**Comment by Timoti** [comment]
I currently have a ruby dude looking at this for me - we're getting close to the source - let you know how that turns out, and dot he sassmiester thing if we still have an issue - THANKS lolmaus

**Comment by Timoti** [comment]
OK - problem isolated to some suzy code in the mix! 
omega theme supports both susy and singularity and I didn't notice layout code I was switching in was susy dependent (the error msg didn't tell me either… so maybe not totally my dufusness!)

thanks for the quick responses guys - as you were…
