### ISSUE TITLE
Nested Properties Error _background-grid.scss

### ISSUE THREAD

**Issue by pducks32** [at-import/Singularity#170]
(Line 224 of _background-grid.scss: Properties are only allowed within rules, directives, mixin includes, or other properties.)

i went to that line and cannot figure out the problem. I'm struggling to get the background-grid to show up and it wasn't so I turned on debug mode and got this.

**Comment by Snugug** [comment]
Can you reproduce this on SassMeister?

**Comment by pducks32** [comment]
http://sassmeister.com/gist/9586820

**Comment by Snugug** [comment]
`background-grid()` needs to be placed within a selector. If you want it on your `body`, place it in your `body` definition. Once scripted `&` lands, we can check to see if it's at the root of your stylesheet and place it in `body` for you, but until then, we can't.
