### ISSUE TITLE
Possible incompatibility between compass and Singularity

### ISSUE THREAD

**Issue by fraincs** [at-import/Singularity#172]
when installing I get through bundler : bundle exec compass create test -r singularitygs --using singularitygs

I get an error    create test/config.rb
Errno::EACCES on line ["891"] of c: Permission denied - (c:/wamp/www/singulartity/test/config.rb20140322-5072-7mq6d0, c:/wamp/www/singulartity/test/config.rb)
Run with --trace to see the full backtrace

seems like this problem : http://stackoverflow.com/questions/22559284/problems-when-creating-compass-project-eacces-on-line-891

I tried using compass 0.12.3 but whatever I do compass 0.12.4 is installed

**Comment by Snugug** [comment]
As per that thread, this appears to be a Compass issue [resolved in 0.12.5](https://github.com/Compass/compass/issues/1618
