### ISSUE TITLE
Last column cut off in Chrome

### ISSUE THREAD

**Issue by grumpit** [at-import/Singularity#173]
In Chrome 33.0.1750.152 with a bare minimum grid set up, the last column is cut off/not the same width as the other columns. The attached screen shots illustrate what I mean.
![screen shot 2014-03-28 at 10 11 17 am](https://cloud.githubusercontent.com/assets/122154/2550411/e468d244-b682-11e3-8fe8-e20ca82efedc.png)
![screen shot 2014-03-28 at 10 07 28 am](https://cloud.githubusercontent.com/assets/122154/2550412/e469fb10-b682-11e3-9dba-46ee06248ffb.png)
Edit: This is only in Chrome, and does not happen in Safari.

**Comment by Snugug** [comment]
It's the background grid representation, not the actual grid. [Grid Background May Be  Inaccurate](https://github.com/Team-Sass/Singularity/wiki/Creating-Grids#grid-backgrounds-may-be-inaccurate)

**Comment by grumpit** [comment]
Apologies. didn't properly RTFB.

**Comment by Snugug** [comment]
No problem, enjoy.
