### ISSUE TITLE
Mixin isolation-span misbehaves with quoted clear value

### ISSUE THREAD

**Issue by jnous** [at-import/Singularity#176]
Previously (in 1.0/1.1) the [documented syntax for isolation-span](https://github.com/Team-Sass/Singularity/wiki/Spanning-The-Grid#isolation-span) was:

``` sass
@include isolation-span(4, 1, 'both');
```

But now, in 1.2.0 quoting the clear value leads to quoting it in the CSS produced, thus causing clearing to fail without an error. Without quotes, it works fine, like:

``` sass
@include isolation-span(4, 1, both);
```

So it should either be documented as not backwards compatible and give a warning or error, or made backwards compatible.

Tested on Sassmeister, please see https://gist.github.com/jnous/10718201.

**Comment by Snugug** [comment]
That's a bug, will fix
