### ISSUE TITLE
Issue with newest version of singularity

### ISSUE THREAD

**Issue by alanburke** [at-import/Singularity#178]
Hi Sam, Scott
Trying out Singularity for the first time.
It might be something that just escaped me when reading the docs, but I've hit this error

<pre>List index is 6 but list is only 5 items long for `nth'</pre>

http://sassmeister.com/gist/11089120 

[Not sure how the asymmetric grids work in any case - still trying to get my head around them - so the error is most likely on my part!]

**Comment by scottkellum** [comment]
You have 5 columns, so spanning 22 columns isn’t possible.

note each number represents a single column: `1 3 5 7 9` < 5 columns in total.

**Comment by alanburke** [comment]
Woah - that was fast! 
I'll get my head around these asymmetric grids yet!
