### ISSUE TITLE
Background grid not showing with Singularity 1.2.1

### ISSUE THREAD

**Issue by richard8** [at-import/Singularity#182]
I'm trying to use Singularity 1.2.1 with Omega 4 in Drupal but can't get the background grid to show. I installed my gems via Bundler, and I'm running "bundle exec compass watch" to compile my Sass files. Everything compiles without errors, and Singularity appears to be working except for the grid not showing. 

Here's what's in my Gemfile:

<pre>
gem 'sass', '~>3.3.0'
gem 'sass-globbing' 
gem 'compass', '~>1.0.0.alpha.18' 
gem 'compass-validator' 
gem 'compass-normalize' 
gem 'compass-rgbapng' 
gem 'singularitygs', '~>1.2.0' 
gem 'toolkit', '~>2.0'
gem 'breakpoint', '~>2.4' 
gem 'oily_png' 
gem 'css_parser' 
</pre>

Here's my layout.scss:

<pre>
@import "compass";
@import "breakpoint";
@import "singularitygs";

@include add-grid(4);
@include add-gutter(0.2);

@include add-grid(8 at 44em);
@include add-grid(12 at 70em);

.l-page {
  @include clearfix;
  @include background-grid;
  margin: 0 auto;
  min-height: 100%;
  max-width: 1200px;
}

@include breakpoint(44em) {
  .l-region--sidebar-first {
    @include grid-span(2,1);
  }
  .l-content {
    @include grid-span(4,3);
  }
  .l-region--sidebar-second {
    @include grid-span(2,7);
  }
}
</pre>

Any ideas what I'm doing wrong? I'm at my wit's end!

**Comment by grayghostvisuals** [comment]
First run `gem list` to make sure you have the recent update for singularity. Your gemfile says 1.2.0, but it was recently fixed ([Issue #168](https://github.com/Team-Sass/Singularity/issues/168#issuecomment-42104677)) so u may have 1.2.0 still installed when u actually need 1.2.1.

**Comment by richard8** [comment]
Good point. Unfortunately, running <code>gem list</code> shows that I do have 1.2.1 installed, so still no joy.

**Comment by grayghostvisuals** [comment]
Can u list the report here when u run `gem list` just for shits and giggles?

**Comment by richard8** [comment]
Sure - here's the full list:

<pre>
*** LOCAL GEMS ***
addressable (2.3.6)
bigdecimal (1.2.4)
breakpoint (2.4.2)
bundler (1.6.2, 1.6.1)
bundler-unload (1.0.2)
chunky_png (1.3.1)
coderay (1.1.0)
compass (1.0.0.alpha.18)
compass-core (1.0.0.alpha.19)
compass-import-once (1.0.4)
compass-normalize (1.5)
compass-rgbapng (0.2.1)
compass-validator (3.0.1)
css_parser (1.3.5)
em-websocket (0.5.1)
eventmachine (1.0.3)
executable-hooks (1.3.1)
ffi (1.9.3)
formatador (0.2.4)
gem-wrappers (1.2.4)
guard (1.8.2)
guard-compass (0.0.8)
guard-livereload (1.4.0)
guard-shell (0.6.1)
http_parser.rb (0.6.0)
io-console (0.4.2)
json (1.8.1)
listen (1.1.0)
lumberjack (1.0.5)
method_source (0.8.2)
minitest (4.7.5)
multi_json (1.9.3)
oily_png (1.1.1)
pry (0.9.12.6)
psych (2.0.3)
rake (10.1.0)
rb-fsevent (0.9.4)
rb-inotify (0.9.4)
rb-kqueue (0.2.2)
rdoc (4.1.0)
rubygems-bundler (1.4.3)
rvm (1.11.3.9)
sass (3.3.7)
sass-globbing (1.1.0)
sassy-maps (0.3.2)
singularitygs (1.2.1)
slop (3.5.0)
test-unit (2.1.1.0)
thor (0.19.1)
toolkit (2.3.0)
yajl-ruby (1.2.0)
</pre>

**Comment by richard8** [comment]
For what it's worth, here's what I have in my config.rb:

<pre>
# Require any additional compass plugins installed on your system.
require 'compass-normalize'
require 'rgbapng'
require 'toolkit'
require 'breakpoint'
require 'singularitygs'
require 'sass-globbing'
</pre>

**Comment by Snugug** [comment]
You need to turn on debug mode for the background grid to show up.

``` scss
@include sgs-change('debug', true);
```

In the future, questions should be looked for (and posed) on StackOverflow per our getting help guidelines.

**Comment by richard8** [comment]
That did it! Thanks so much, Snugug. Sorry for posting in the wrong place -- I'll use StackOverflow in the future.
