### ISSUE TITLE
Support for sass 3.3

### ISSUE THREAD

**Issue by Anenth** [at-import/Singularity#185]
Why is singularity not supporting sass3.3 ?

**Comment by lolmaus** [comment]
It does. Modern versions of Singularity depend on Sass 3.3. See https://rubygems.org/gems/singularitygs

Probably, you have a legacy version locked in your `Gemfile.lock`. Check your `Gemfile` to reference the current version, then run `bundle update`.

**Comment by Anenth** [comment]
Singularity 1.1.x requires Sass 3.2.x and Compass 0.12.x and is incompatible with Sass 3.3.x.
https://github.com/Team-Sass/Singularity/wiki/Installation#requirements

**Comment by lolmaus** [comment]
That's correct. FYI, current version is 1.2.1.

**Comment by Anenth** [comment]
Hoo thats the catch ! thanks

**Comment by scottromack** [comment]
That stumbled me also..

**Comment by lolmaus** [comment]
It's really sad that @Snugug decided not to maintain a separate git branch for Singularity 1.1.x. The latest Singularity 1.1.x release has confirmed bugs that have only been fixed in Singularity 1.2.x, incompatible with Sass 3.2. :sob:

Also, SemVer was violated treacherously. :(
