### ISSUE TITLE
Installation for non-Ruby projects

### ISSUE THREAD

**Issue by emersonthis** [at-import/Singularity#188]
I can't find any documentation for non-Ruby / non-compass / etc projects. Would it be possible to include a /dist directory with the compiled scss to @import into an existing project?

**Comment by scottkellum** [comment]
Find it here: https://github.com/Team-Sass/Singularity/tree/1.x.x/stylesheets

Note you MUST be running Sass 3.3 or compatible. This will NOT work with libsass.

**Comment by Snugug** [comment]
I also think there may be a misunderstanding of what Singularity is. Singularity is not a Bootstrap-style grid, something we call a CSS System grid, it's a CSS Framework that doesn't have a grid to compile by itself but rather is designed as a way for you to create the grid you need.

**Comment by emersonthis** [comment]
Good point. The way I phrased my question didn't make sense. I'm really 
just trying to figure out how to use Singularity with a PHP project that 
isn't managed by Compass or other package management tools.

Snugug wrote:

**Comment by lolmaus** [comment]
@s-d-p, you can totally use Compass in your PHP environment! You don't need to integrate them together, just use them alongside each other!

In short:
1. Have Ruby installed on your system.
2. Install Bundler: `gem install bundler`.
3. Create a `Gemfile` in the root of your project, list your Compass dependencies there.
4. Install those dependencies by running `bundle install`.
5. Create a Compass' `config.rb` in the root of your project, set up paths and stuff, require dependencies.
6. In the root of your project run `bundle exec compass watch`. CSS will be generated as you modify your Sass code, provided that the watcher is running.

That's it! Note that if you check the compiled CSS into your version control, you won't need Ruby serverside. But storing auto-generated files in VCS is generally considered a bad practice, so consider integrating Sass compilation into your deployment routine.

**Comment by emersonthis** [comment]
@lolmaus That's a good point. I'm not sure if the team I'm working for 
would be okay with me doing that. But I'll ask.

lolmaus wrote:
