### ISSUE TITLE
Add Compass requirements back

### ISSUE THREAD

**Issue by scottkellum** [at-import/Singularity#19]
Compass background mixin needs to be added back in. Audit what else might need to be imported as well.

**Comment by Snugug** [comment]
Importing @compass at the top of the gem should come w/that, no?

**Comment by scottkellum** [comment]
Not the Compass mixin, no. Needs to be imported into the Sass file not the gem file. Can probably do from the main singularity file.

**Comment by Snugug** [comment]
Right, [line 2 of the Sass file](https://github.com/scottkellum/Singularity/blob/master/stylesheets/singularitygs.sass) should import all of Compass; does that not include the background mixin?

**Comment by scottkellum** [comment]
Ah, yeah that should work, was using an old gem.

Might want to fine tune this later for speed.
