### ISSUE TITLE
The `sgs-reset()` mixin should allow resetting multiple values with one call

### ISSUE THREAD

**Issue by lolmaus** [at-import/Singularity#191]
Current syntax:

```
+sgs-reset(grids)
+sgs-reset(gutters)
```

Suggested syntax:

```
+sgs-reset(grids gutters)
```

I often use multiple different grids on one page and i find myself resetting the grid all the time. It would be awesome to make the reset easier to use.

**Comment by lolmaus** [comment]
Thank you Sam.

**Comment by Snugug** [comment]
n/p
