### ISSUE TITLE
Bug: float-span spans the last column incorrectly when used with asymmetric grid

### ISSUE THREAD

**Issue by lolmaus** [at-import/Singularity#192]
## How to reproduce

``` sass
@import "singularitygs"

+add-grid(3 1)
+add-gutter(0)

.foo
  +float-span(1,1)

.bar
  +float-span(1,2)
```
## Expected output

``` css```
.foo {
  width: 75%;
  /* ... */
}

.bar {
  width: 25%;
  /* ... */
}
```
## Actual output

``` css```
.foo {
  width: 75%;
  /* ... */
}

.bar {
  width: 75%;
  /* ... */
}
```

If you use an asymmetric grid with more columns, you'll notice that the last column gets the width of the last-but-one column.
## Sassmeister demo

http://sassmeister.com/gist/761cb758b455e21a903f

**Comment by iamcarrico** [comment]
Fixed in 6c4851e7a141aa0a22e24fe527f85fe51b55c5af
