### ISSUE TITLE
"grid-toggle" mixin was removed

### ISSUE THREAD

**Issue by iamcarrico** [at-import/Singularity#195]
Should we re-add it, or update the docs to reflect that change? 

It was removed here: https://github.com/Team-Sass/Singularity/commit/aea6d0ab0f62b52f1dac84d36db3633a64d2168a

**Comment by Snugug** [comment]
It was never really documented and never really worked correctly, we should probably remove from docs.

**Comment by grayghostvisuals** [comment]
Thanks again @iamcarrico for the help and info on IRC today. :beers:

**Comment by Snugug** [comment]
[Resolved](https://github.com/Team-Sass/Singularity/wiki/Creating-Grids#visualizing-your-grids)

**Comment by lolmaus** [comment]
`grid-toggle` is still mentioned on that page, is it intentional?

**Comment by Snugug** [comment]
Yup, that was unintentional, going to fix now.
