### ISSUE TITLE
Better Debug Guidelines

### ISSUE THREAD

**Issue by Snugug** [at-import/Singularity#20]
It seems as if the `background-grid` mixin isn't so smart, especially with non-uniform grids, and we should come up with a better mixin for this.

**Comment by scottkellum** [comment]
Works with non-uniform grids for me, kinda sucks though. Variables need to be tweaked a little to get passed through. Would like to add a way to view padding to this.

**Comment by Snugug** [comment]
Hmm, I just tried it with a non-uniform grid, did `(4, 1, red)` and it gave me 4 uniform sized columns. Is there something I'm missing there? Maybe it's just that the documentation needs to be better?

**Comment by scottkellum** [comment]
$columns, $gutter, $color

you might have wanted to do
((4, 1), $color: red)

**Comment by Snugug** [comment]
Nope, that's now giving me an asymetrical grid, but it's not the right grid.

**Comment by scottkellum** [comment]
Not clear what you want, the first column there should be 4x the last column. (just two columns)

**Comment by Snugug** [comment]
Oh! So do I need to put in my full columns stuff?

**Comment by Snugug** [comment]
Yup, yup, that's what I needed to do.
So I guess, either better docs for this, or make it smarter?

**Comment by scottkellum** [comment]
Want to pull existing vars? should work without anything (). unless some vars aren’t being pulled properly.

**Comment by Snugug** [comment]
So it does. so it does.
