### ISSUE TITLE
Multiline grid: some items are shifted above their neighbour

### ISSUE THREAD

**Issue by ghost** [at-import/Singularity#200]
I recently found out that when you wnat to create a responsive grid the singularity way of columns is not working out very well.

When you have six items that vary in hight and you want to have them float in a 3 column grid this would be the way to write it:

.item:nt-child(3n+1) {
  @include grid-span(4, 1);
  clear: left;
}
.item:nt-child(3n+2) {
  @include grid-span(4, 5);
  clear: left;
}
 .item:nt-child(3n+3) {
  @include grid-span(4, 9);
  clear: left;
} 

But when the right item of the first line is higher then one of the others, the last item of the next row is rendered on top of it's neighbour: the exception on the rule - last column floated right - is not recognized as being on the same line.

Is there a way to work around this?

**Comment by Snugug** [comment]
Please provide a code example on Sassmeister

**Comment by ghost** [comment]
Which one?

**Comment by Snugug** [comment]
Please provide a code example on Sassmeister illustrating your issue

**Comment by mnich** [comment]
@erlendoos use this http://sassmeister.com/gist/2971f26fd013eaaf23aa for your example

**Comment by finteractive** [comment]
I'm pretty sure you want to clear right the first item, and none of the other ones...

.item:nth-child(3n+1) {
@include grid-span(4, 1);
background: red;
clear: right;
}

.item:nth-child(3n+2) {
@include grid-span(4, 5);
background: blue;
}
.item:nth-child(3n+3) {
@include grid-span(4, 9);
background: green;
}

http://sassmeister.com/gist/af6f1f1bc757a6cd5e38

**Comment by scottkellum** [comment]
Just using floats without any grid system may be the simplest solution.

**Comment by mnich** [comment]
look this version with floats 

http://sassmeister.com/gist/0cee713988a358bd4a97

**Comment by ghost** [comment]
It is not about the clear, it is about the combination of float left and
float right.

All should float left to make this work for variable height cells.

I need grid span for the list is responsive. 1 column, > 400px 2column, >
600px 3 column, > 800px 4 column.
If this was not the case I could have done it with div.wrapper > div.row >
div.cell

This works when you use float left for all cells, OR float right for all
cells.

What advantage does it have to have the last column float=right?

from my code example I expect all to be float left. the last column is
floated right intentionally by singularity. I wonder why, and if I can
choose to use only float left.

2014-11-17 18:55 GMT+01:00 Artur Leśniewski notifications@github.com:

**Comment by Snugug** [comment]
@erlendoos Please provide a reduced use case example of either your your _current_ code not working of what you _expect_ the code to look like. I cannot help you until you've done so.

As for why the last item is floated right, it's done to hide rounding issues in browsers and ensure that the right edge of the last item in a row is always flush. This is especially an issue in Webkit and older versions of Blink and Internet Explorer. It's less noticeable in Isolation output than it is in Float, but still there.

**Comment by ghost** [comment]
<a href="http://sassmeister.com/gist/988818485c6af68a0ecf">Current (not working) code</a>

**Comment by ghost** [comment]
And floating all left:
<a href="http://sassmeister.com/gist/2235dc933d5b95505498">Problem solved.</a>

**Comment by Snugug** [comment]
It sounds like what you want is a traditional floating grid instead of an Isolation grid. Using `float-span` for these elements will do exactly what you'd like.

http://sassmeister.com/gist/fe97d187a1aebd1d4aa5

**Comment by ghost** [comment]
Looks great!
Thanks!

2014-11-17 20:57 GMT+01:00 Sam Richard notifications@github.com:
