### ISSUE TITLE
api/_calc.scss: Functions can only contain variable declarations and control directives.)

### ISSUE THREAD

**Issue by heaversm** [at-import/Singularity#204]
I get the error running `bundle exec compass watch` on a brand new project where no singularity commands or variables have yet been set (in other words, the error occurs by simply including singularity):

```
error build/public/sass/main.scss (Line 13 of /Users/mikeheavers/.rvm/gems/ruby-2.2.0/gems/singularitygs-1.5.1/stylesheets/singularitygs/api/_calc.scss: Functions can only contain variable declarations and control directives.)
```

I am using this within my main .scss file:

`@import "singularitygs";`

this within config.rb:

`require "singularitygs" #grid system`

and this within the gemfile:

`gem "singularitygs", "~>1.4"`

Any idea what's going on here and how to fix it?

**Comment by lolmaus** [comment]
Please report your Sass version.

**Comment by heaversm** [comment]
Sass 3.3.14

gem 'compass', '~>1.0.3'

**Comment by Snugug** [comment]
Sass 3.4 introduces `@error` which is being used there but is not supported in Sass 3.3, which I'm assuming it's treating like a CSS `@directive`, much like `@media`. I should be testing for `@error` before calling it, and will update the code, but updating to 3.4 will resolve this issue.

**Comment by heaversm** [comment]
Hi - I'm using the breakpoint module, which depends on sass 3.3.0.rc.2, so using a higher version of SASS might not be an option for me. Is there anything else I can do to resolve the issue?

**Comment by Snugug** [comment]
Breakpoint 2.5.0 requires Sass >= 3.3.0.rc.2 so can be installed with 3.4.x. What version of Breakpoint are you using?

**Comment by heaversm** [comment]
I was using 2.4. Upgrading fixed it. Thanks!

On Wed, Feb 18, 2015 at 1:05 PM, Sam Richard notifications@github.com
wrote:

> Breakpoint 2.5.0 requires Sass >= 3.3.0.rc.2 so can be installed with
> 3.4.x. What version of Breakpoint are you using?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/at-import/Singularity/issues/204#issuecomment-74937444
> .

## 

Mike Heavers
mikeheavers.com
917-345-6634
