### ISSUE TITLE
Invalid US-ASCII character "\xC3" in singularitygs-1.6.2/stylesheets/singularitygs/helpers/_str-replace.scss

### ISSUE THREAD

**Issue by cyberswat** [at-import/Singularity#207]
My monitoring awoke me to this .. any chance you can help me correlate what was in your release yesterday that would cause this?

[31m    error[0m scss/print.scss (Line 7 of /retracted/shared/bundle/ruby/1.9.1/gems/singularitygs-1.6.2/stylesheets/singularitygs/helpers/_str-replace.scss: Invalid US-ASCII character "\xC3")
[31m    error[0m scss/style.scss (Line 7 of /retracted/shared/bundle/ruby/1.9.1/gems/singularitygs-1.6.2/stylesheets/singularitygs/helpers/_str-replace.scss: Invalid US-ASCII character "\xC3")
[31mCompilation failed in 2 files.

**Comment by cyberswat** [comment]
@Snugug any help understanding what I'm dealing with here would be fantastic.

**Comment by cyberswat** [comment]
http://paulchr.ablass.me/blog/schlagworte/encoding/

**Comment by cyberswat** [comment]
```
[root@web01 cyberswat]# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by Snugug** [comment]
There is a comment on line 7 of the string replace helper that includes someone's name that has an é in it. That appears to be the problem you're running into as it's not a US character.

https://github.com/at-import/Singularity/blob/1.x.x/stylesheets/singularitygs/helpers/_str-replace.scss#L7

**Comment by cyberswat** [comment]
awesome .. that was super helpful.

**Comment by Snugug** [comment]
That resolve this issue?

**Comment by cyberswat** [comment]
My challenge is that I don't do development with this gem or sass. I've reverted our systems to version 1.5.1 that does not have this issue and am restoring the deployments affected by this.  We picked this up in a testing environment so it was caught relatively early.

I do agree with you that the character in that comment is the culprit. From what I could tell the encoding on the server is set properly and explicitly setting it in the file that is invoking singularity did not resolve the issue.

I'll get someone to look at this this morning.

**Comment by Snugug** [comment]
Sounds good, keep me posted. FWIW that character has no impact on actually being able to use the code in that file (assuming you can get past the encoding error you seem to be having).

**Comment by aliyakhan** [comment]
any update here? Getting same issue.

**Comment by Snugug** [comment]
If you can, I recommend using `utf-8` instead of `us-ascii` for Singularity (really in general), but I'll look into pushing a point release today that removes the non-`us-ascii` character

**Comment by aliyakhan** [comment]
Yeah did that already. Thx

**Comment by GuyPaddock** [comment]
Any updates on this issue? We just started seeing it as well.

**Comment by Arvoreen** [comment]
I was able to get past this by adding the following line to the end of my config.rb file:

Encoding.default_external = 'UTF-8'

**Comment by rmcveigh** [comment]
Adding `Encoding.default_external = 'UTF-8'` to my config.rb file worked for me as well. Thanks Arvoreen.

**Comment by shawnzhu** [comment]
@Arvoreen 's fix works for me as well

**Comment by alvinpascoe** [comment]
Excellent, thanks @Arvoreen. Works great for me too.
