### ISSUE TITLE
"stack level too deep" when background-grid and too much columns

### ISSUE THREAD

**Issue by tomagladiator** [at-import/Singularity#208]
Hello,

I find an issue when I tried to add more than 19 grid : **@include add-grid(24);**
AND
I add the background-grid in the same time.
A message appears **"stack level too deep"**

The way I fixed it is to comment in **_background-grid.scss** the **line 209**:
**//$SVG: url-encode($SVG);**

I don't know why, but with this fix, everything works.

Thanks

**Comment by Snugug** [comment]
Are you using Ruby Sass or Node Sass?

**Comment by Vagelis-Prokopiou** [comment]
I, all of a sudden, started having the same issue when I declared a 16 column grid. I had a "stack level too deep" error. I could not understand what is going on. I thought something went bad with my ruby environment.

The exact error is: “SystemStackError on line ["23"] of /var/lib/gems/1.9.1/gems/sass-3.4.13/lib/sass/script/value/base.rb: stack level too deep”.

Commenting out the "//$SVG: url-encode($SVG);" line, did not work for me.

I have sass-3.4.13 and singularitygs-1.6.2 installed. The same problem happens with newer versions of ruby than 1.9.1.

**Comment by Snugug** [comment]
Okay, this is most likely coming from the new SVG code for background grids.
For 1.7.0 I'm going to write a ruby version of `url-encode` that should resolve this issue without breaking compatibility, as well as an Eyeglass one for Node

**Comment by Vagelis-Prokopiou** [comment]
Thank you Snugug. Thank you for your hard work.

**Comment by C13L0** [comment]
Agree with Vaggos. Thank you!

**Comment by ezekg** [comment]
@Snugug, it actually might be from your `str-replace()` function being called on such a large string. I added a Ruby function for it for Flint (using the same technique for grid overlays) and it decreased my tests from ~80s to ~15s. Then again, that's essentially all `url-encode()` does.

``` ruby
#
# Replace substring with string
#
# @param {String} string  - string that contains substring
# @param {String} find    - substring to replace
# @param {String} replace - new string to replace sub with
#
# @return {String}
#
def ruby_str_replace(string, find, replace)
  assert_type string, :String, :string
  assert_type find, :String, :find
  assert_type replace, :String, :replace

  Sass::Script::String.new(string.value.gsub(find.value, replace.value))
end
declare :ruby_str_replace, :args => [:string, :find, :replace]
```

**Comment by Snugug** [comment]
Yah, that’s what the problem is. I’m going to write JS and Ruby functions for it, just no time ATM  

## 

Sam Richard
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
