### ISSUE TITLE
Container?

### ISSUE THREAD

**Issue by Snugug** [at-import/Singularity#21]
Unlike Susy, Singularity doesn't seem to have a container mixin (at least not one I could see). Interested in adding one in? It also may make doing things like having adjustable grid layouts at different breakpoints more feasible.

**Comment by scottkellum** [comment]
What would this do that `position: relitive` doesn’t do? I didn’t want to put a defined wrapper type in because it felt restrictive. Open to it if it has advantages though.

**Comment by Snugug** [comment]
Susy's container adds a bunch of IE hacks in as well as has the possibility to set a max width and center everything, but primarily the IE hacks

**Comment by scottkellum** [comment]
Cool, yeah this shit needs some hard core IE testing anyway.

**Comment by Snugug** [comment]
Haha yes, yes it probably does. :P

**Comment by Snugug** [comment]
This is in master. We need to figure out how we're going to handle base font sizes, but this is in master.
