### ISSUE TITLE
Rows and columns of items, using floatspan

### ISSUE THREAD

**Issue by minneapolisdan** [at-import/Singularity#210]
I can create some mixins to create columns of list items, as I've done here, http://sassmeister.com/gist/4646bfef95258fd834ef . HTML list items in 3 columns for desktop, 2 columns for tablets, etc.

But if one of my list items in a row is too long, the rest of the rows get broken up. To resolve this in the past, I've used "display:inline-block" instead of floats. I can't seem to get this working right with Singularity, however. When I try, the percentages no longer work. 

I want to use the percentages of width and margin that Singularity gives me, but with inline-block, instead of float. Does that make sense? Or is there another way? 

https://www.dropbox.com/s/8ic8s2lfqk5eg89/Screenshot%202015-05-12%2014.11.13.png?dl=0

**Comment by Snugug** [comment]
Singularity does not support a `inline-block` output style out of the box. It does have an API that allows you to build your own output styles. Take a look at how they're currently built, and you can build your own

https://github.com/at-import/Singularity/tree/1.x.x/stylesheets/singularitygs/api
