### ISSUE TITLE
Node-sass failing with Bus error 10

### ISSUE THREAD

**Issue by Nooshu** [at-import/Singularity#211]
Hello,

I've just run into an issue that kills node-sass. Adding these lines together ends in node-sass giving a 'bus error'. When each line is added on its own it doesn't crash.

```
@import '../../../../../../bower_components/singularity/stylesheets/singularitygs';

@include sgs-change('debug', true);
@include background-grid();
```

It gives the following console error:

```
node-sass   3.1.2   (Wrapper)   [JavaScript]
libsass     3.2.4   (Sass Compiler) [C/C++]

Loading "sass.js" tasks...OK
+ sass

Running "sass" task

Running "sass:dist" (sass) task
Verifying property sass.dist exists in config...OK
Files: build/src/etc/designs/project/sass/test.scss -> build/dist/etc/designs/project/css/test.css
Options: precision=10, sourceMap, outputStyle="expanded"
[1]    69434 bus error  grunt sass --v
```

I've also attached the log from OSX available [here](https://gist.github.com/Nooshu/ca2185cdb0ec818b0103)

It only seems to have started happening in the last week or so, so i'm not sure what has changed. Hopefully that helps, it was a bit of a pain to debug!

Note: It's also worth noting that this only crashes node-sass on OSX. Running it inside Vagrant using Ubuntu 14.04 it runs fine.

Thanks.

**Comment by the-Dean** [comment]
I just posted the same issue, but with one difference, its using these two lines together that causes the issue
    @include sgs-change('debug', true);
    @include background-grid();
Did you find a solution for it?

**Comment by humanaut** [comment]
I just encountered this issue also.

**Comment by digitaldonkey** [comment]
Any solution?
