### ISSUE TITLE
I'm ... lost? My thoughts on deciding whether to use this or not

### ISSUE THREAD

**Issue by replete** [at-import/Singularity#212]
Some feedback:
- This system looks awesome.
- I traversed a lot of documentation, and still don't understand quite how I should use it. Do I define a grid system and then render the markup myself? Etc. Make this clearer by simplifying the paradigm needed to use the system.
- I expected to see some real CSS with examples of use-cases. Showing the output is the key thing to understanding how it works.
- Because I don't quite get it even after 10 minutes of reading pages and documentation, I'm now concerned about whether to use it or not. I really really want to, but I feel like I need to spend an evening with it. Just show me how to create a set of usable grid classes like foundation or zurb etc. I want to see markup.

Please don't take this as negative criticism, from what I _think_ I understand about this system - it looks very elegant. But making a typical use-case more obvious would help.

Great work guys

**Comment by Vagelis-Prokopiou** [comment]
Hello my friend.
You should definitely use this grid system. It is just awesome!

You will need a little more than 10 minutes of reading to get the grasp of it, but if you do, the sky is the limit.

This videos may help you.
https://www.youtube.com/watch?v=PDbVpyS6jF0
https://www.youtube.com/watch?v=uqINlCBe2NE
https://vimeo.com/63509346

I provide some real code too, to see it in action.

My _grid.scss partial:
@import "singularitygs";

@include add-grid(12);
@include add-gutter(1/3);

$mobile-landscape: 37.5em; // (600px)
$tablet: 48em; // (768px)
$desktop: 75em; // (1200px)

My _footer.scss partial:
.l-footer {

```
h1, h2, h3, h4, h5, p {
    color: #FFF;
}

h2 {
    margin-bottom: -40px;
}



#block-block-4 { // RSS
    float: left;
    @include breakpoint($mobile-landscape) {
        @include grid-span(4, 1);
    }   
}

#block-block-25 { // Youtube
    float: right;
    @include breakpoint($mobile-landscape) {
        @include grid-span(4, 5);
    }   
}

#block-block-33 { // Mailchimp
    @include grid-span(12, 1);
    h2 {
        margin-bottom: -5px;
    }
    @include breakpoint($mobile-landscape) {
        @include grid-span(4, 9);
    }   
}

#block-block-1 { // Designed by.
    @include grid-span(12, 1);
    @include breakpoint($tablet) {
        @include grid-span(8, 3);
        clear: both;
    }   
}

#block-block-36 { // Powered by(custom)
    //@include grid-span(12, 1);
    margin-top: 50px;
    clear: both;

    img {
        display: inline-block;
        max-height: 25px !important;
        width: auto !important;
    }

    @include breakpoint($tablet) {
        @include grid-span(12, 1);
        clear: both;
        img {
            display: inline-block;
            max-height: 35px !important;
            width: auto !important;
        }
    }

    @include breakpoint($desktop) {
        @include grid-span(12, 1);
        clear: both;
        img {
            display: inline-block;
            max-height: 80px !important;
            width: auto !important;
        }
    }

}
```

}

The final css including all the imported partials:
@charset "UTF-8";
/\* No files to import found in abstractions/*_\/_ _/
/_ line 1, ../sass/base/_media.scss */
img, media {
  max-width: 100% !important;
  height: auto !important;
  vertical-align: top; }

/\* line 1, ../sass/base/_tables.scss */
table {
  border: none; }

/\* line 5, ../sass/base/_tables.scss */
th {
  padding: 20px;
  text-align: center;
  border: 1px solid black; }

/\* line 11, ../sass/base/_tables.scss */
tr {
  border-bottom: 1px solid black; }

/\* line 15, ../sass/base/_tables.scss */
td {
  padding: 20px;
  border-right: 1px solid black; }

/\* line 20, ../sass/base/_tables.scss */
td:first-of-type {
  border-left: 1px solid black; }

@font-face {
  font-family: 'sbl_greekregular';
  src: url("../sbl_grk-webfont/sbl_grk-webfont.eot");
  src: url("../sbl_grk-webfont/sbl_grk-webfont.eot?#iefix") format("embedded-opentype"), url("../sbl_grk-webfont/sbl_grk-webfont.woff2") format("woff2"), url("../sbl_grk-webfont/sbl_grk-webfont.woff") format("woff"), url("../sbl_grk-webfont/sbl_grk-webfont.ttf") format("truetype");
  font-weight: normal;
  font-style: normal; }
/\* line 15, ../sass/base/_typography.scss */
body {
  font-family: sbl_greekregular, Georgia, Serif;
  font-size: 100%;
  color: black; }

/\* line 22, ../sass/base/_typography.scss */
h1 {
  font-size: 2.28em;
  line-height: 1.98em; }

/\* line 27, ../sass/base/_typography.scss */
h2 {
  font-size: 1.68em;
  line-height: 1.98em; }

/\* line 32, ../sass/base/_typography.scss */
h3 {
  font-size: 1.44em;
  line-height: 1.98em; }

/\* line 37, ../sass/base/_typography.scss */
h4 {
  font-size: 1.32em;
  line-height: 1.8em; }

/\* line 42, ../sass/base/_typography.scss */
p, ul, ol {
  font-size: 1.2em;
  line-height: 1.8em; }

/\* line 47, ../sass/base/_typography.scss _/
a {
  color: #e54e4b;
  text-decoration: none;
  -moz-transition: all 0.5s ease;
  -o-transition: all 0.5s ease;
  -webkit-transition: all 0.5s ease;
  transition: all 0.5s ease; }
  /_ line 52, ../sass/base/_typography.scss */
  a:hover {
    color: red; }

@media (min-width: 37.5em) {
  /\* line 3, ../sass/components/_article.scss _/
  body.node-type-article .pane-views-see-also-block {
    width: 31.91489%;
    float: left;
    margin-right: -100%;
    margin-left: 0;
    clear: none; } }
@media (min-width: 37.5em) {
  /_ line 9, ../sass/components/_article.scss _/
  body.node-type-article .pane-views-popular-block {
    width: 31.91489%;
    float: left;
    margin-right: -100%;
    margin-left: 34.04255%;
    clear: none; } }
@media (min-width: 37.5em) {
  /_ line 15, ../sass/components/_article.scss _/
  body.node-type-article .pane-node-field-pdf,
  body.node-type-article .pane-service-links-service-links,
  body.node-type-article .pane-node-field-tags {
    width: 31.91489%;
    float: right;
    margin-left: 0;
    margin-right: 0;
    clear: none;
    clear: right; } }
/_ line 24, ../sass/components/_article.scss _/
body.node-type-article .pane-block-12 {
  clear: both; }
/_ line 28, ../sass/components/_article.scss */
body.node-type-article .pane-disqus-disqus-comments,
body.node-type-article .pane-disqus-disqus-recent-comments {
  width: 100%;
  float: right;
  margin-left: 0;
  margin-right: 0;
  clear: none;
  clear: both; }

/\* line 3, ../sass/components/_bibliography.scss _/
body.page-βιβλιογραφία .view-bibliography,
body.page-βιβλιογραφία .view-row,
body.page-βιβλιογραφία .views-row,
body.page-βιβλιογραφία .views-row-1,
body.page-βιβλιογραφία .views-row-odd,
body.page-βιβλιογραφία .views-row-even,
body.page-βιβλιογραφία .views-row-first,
body.page-βιβλιογραφία .views-row-last,
body.page-βιβλιογραφία .views-field,
body.page-βιβλιογραφία .views-field-field-image {
  overflow: hidden;
  *zoom: 1; }
/_ line 16, ../sass/components/_bibliography.scss _/
body.page-βιβλιογραφία h2 {
  padding: 0;
  margin: 0;
  margin-bottom: 10px;
  line-height: 1.2em; }
/_ line 23, ../sass/components/_bibliography.scss _/
body.page-βιβλιογραφία img {
  border: 1px solid black; }
/_ line 28, ../sass/components/_bibliography.scss _/
body.page-βιβλιογραφία .views-row {
  margin-top: 0;
  margin-bottom: 50px !important;
  clear: both; }
@media (min-width: 37.5em) {
  /_ line 34, ../sass/components/_bibliography.scss _/
  body.page-βιβλιογραφία .views-field-field-image {
    margin-right: 20px;
    width: 23.40426%;
    float: left;
    margin-right: -100%;
    margin-left: 0;
    clear: none; } }
@media (min-width: 48em) {
  /_ line 34, ../sass/components/_bibliography.scss _/
  body.page-βιβλιογραφία .views-field-field-image {
    margin-top: 0px;
    width: 14.89362%;
    float: left;
    margin-right: -100%;
    margin-left: 0;
    clear: none; } }
/_ line 46, ../sass/components/_bibliography.scss _/
body.page-βιβλιογραφία .bibliography-wrapper {
  margin-top: 5px; }
  @media (min-width: 37.5em) {
    /_ line 46, ../sass/components/_bibliography.scss _/
    body.page-βιβλιογραφία .bibliography-wrapper {
      width: 65.95745%;
      float: left;
      margin-right: -100%;
      margin-left: 25.53191%;
      clear: none; } }
  @media (min-width: 48em) {
    /_ line 46, ../sass/components/_bibliography.scss _/
    body.page-βιβλιογραφία .bibliography-wrapper {
      width: 74.46809%;
      float: left;
      margin-right: -100%;
      margin-left: 17.02128%;
      clear: none; } }
/_ line 57, ../sass/components/_bibliography.scss _/
body.page-βιβλιογραφία .pane-block-34 {
  clear: both; }
/_ line 61, ../sass/components/_bibliography.scss _/
body.page-βιβλιογραφία table {
  width: 100%;
  max-width: 100%; }
/_ line 66, ../sass/components/_bibliography.scss */
body.page-βιβλιογραφία td {
  padding: 5px; }

/\* line 3, ../sass/components/_book.scss _/
body.node-type-book .panel-col-first {
  width: 100%;
  float: right;
  margin-left: 0;
  margin-right: 0;
  clear: none;
  margin-bottom: 20px;
  clear: both; }
/_ line 9, ../sass/components/_book.scss _/
body.node-type-book .panel-col-last {
  width: 100%;
  float: right;
  margin-left: 0;
  margin-right: 0;
  clear: none;
  margin-bottom: 20px;
  clear: both; }
@media (min-width: 37.5em) {
  /_ line 16, ../sass/components/_book.scss _/
  body.node-type-book .panel-col-first {
    width: 65.95745%;
    float: right;
    margin-left: 0;
    margin-right: 0;
    clear: none; }
  /_ line 20, ../sass/components/_book.scss */
  body.node-type-book .panel-col-last {
    width: 31.91489%;
    float: left;
    margin-right: -100%;
    margin-left: 0;
    clear: none; } }

/\* line 3, ../sass/components/_epiloges.scss _/
body.page-επιλογές .panel-panel {
  width: 100%;
  float: right;
  margin-left: 0;
  margin-right: 0;
  clear: none;
  clear: both; }
/_ line 8, ../sass/components/_epiloges.scss _/
body.page-επιλογές .panel-col-first {
  width: 100%;
  float: right;
  margin-left: 0;
  margin-right: 0;
  clear: none;
  clear: both; }
/_ line 13, ../sass/components/_epiloges.scss _/
body.page-επιλογές .panel-col-last {
  width: 100%;
  float: right;
  margin-left: 0;
  margin-right: 0;
  clear: none;
  clear: both; }
@media (min-width: 37.5em) {
  /_ line 19, ../sass/components/_epiloges.scss _/
  body.page-επιλογές .panel-col-first {
    width: 48.93617%;
    float: right;
    margin-left: 0;
    margin-right: 0;
    clear: none; }
  /_ line 23, ../sass/components/_epiloges.scss _/
  body.page-επιλογές .panel-col-last {
    width: 48.93617%;
    float: left;
    margin-right: -100%;
    margin-left: 0;
    clear: none; }
  /_ line 27, ../sass/components/_epiloges.scss _/
  body.page-επιλογές .panel-col-bottom {
    margin-top: 50px;
    clear: both; } }
  @media (min-width: 37.5em) and (min-width: 37.5em) {
    /_ line 32, ../sass/components/_epiloges.scss _/
    body.page-επιλογές .panel-col-bottom .pane-clone-10-of {
      width: 31.91489%;
      float: left;
      margin-right: -100%;
      margin-left: 0;
      clear: none;
      clear: left; }
    /_ line 37, ../sass/components/_epiloges.scss _/
    body.page-επιλογές .panel-col-bottom .pane-clone-17-of {
      width: 31.91489%;
      float: left;
      margin-right: -100%;
      margin-left: 34.04255%;
      clear: none; }
    /_ line 42, ../sass/components/_epiloges.scss _/
    body.page-επιλογές .panel-col-bottom .pane-clone-18-of {
      width: 31.91489%;
      float: right;
      margin-left: 0;
      margin-right: 0;
      clear: none; }
    /_ line 47, ../sass/components/_epiloges.scss _/
    body.page-επιλογές .panel-col-bottom .pane-darwin {
      width: 31.91489%;
      float: left;
      margin-right: -100%;
      margin-left: 0;
      clear: none;
      clear: left; }
    /_ line 52, ../sass/components/_epiloges.scss */
    body.page-επιλογές .panel-col-bottom .pane-pascal {
      width: 31.91489%;
      float: left;
      margin-right: -100%;
      margin-left: 34.04255%;
      clear: none; } }

/\* line 4, ../sass/components/_footer.scss _/
.l-footer h1, .l-footer h2, .l-footer h3, .l-footer h4, .l-footer h5, .l-footer p {
  color: #FFF; }
/_ line 8, ../sass/components/_footer.scss _/
.l-footer h2 {
  margin-bottom: -40px; }
/_ line 14, ../sass/components/_footer.scss _/
.l-footer #block-block-4 {
  float: left; }
  @media (min-width: 37.5em) {
    /_ line 14, ../sass/components/_footer.scss _/
    .l-footer #block-block-4 {
      width: 31.91489%;
      float: left;
      margin-right: -100%;
      margin-left: 0;
      clear: none; } }
/_ line 21, ../sass/components/_footer.scss _/
.l-footer #block-block-25 {
  float: right; }
  @media (min-width: 37.5em) {
    /_ line 21, ../sass/components/_footer.scss _/
    .l-footer #block-block-25 {
      width: 31.91489%;
      float: left;
      margin-right: -100%;
      margin-left: 34.04255%;
      clear: none; } }
/_ line 28, ../sass/components/_footer.scss _/
.l-footer #block-block-33 {
  width: 100%;
  float: right;
  margin-left: 0;
  margin-right: 0;
  clear: none; }
  /_ line 30, ../sass/components/_footer.scss _/
  .l-footer #block-block-33 h2 {
    margin-bottom: -5px; }
  @media (min-width: 37.5em) {
    /_ line 28, ../sass/components/_footer.scss _/
    .l-footer #block-block-33 {
      width: 31.91489%;
      float: right;
      margin-left: 0;
      margin-right: 0;
      clear: none; } }
/_ line 38, ../sass/components/_footer.scss _/
.l-footer #block-block-1 {
  width: 100%;
  float: right;
  margin-left: 0;
  margin-right: 0;
  clear: none; }
  @media (min-width: 48em) {
    /_ line 38, ../sass/components/_footer.scss _/
    .l-footer #block-block-1 {
      width: 65.95745%;
      float: left;
      margin-right: -100%;
      margin-left: 17.02128%;
      clear: none;
      clear: both; } }
/_ line 46, ../sass/components/_footer.scss _/
.l-footer #block-block-36 {
  margin-top: 50px;
  clear: both; }
  /_ line 51, ../sass/components/_footer.scss _/
  .l-footer #block-block-36 img {
    display: inline-block;
    max-height: 25px !important;
    width: auto !important; }
  @media (min-width: 48em) {
    /_ line 46, ../sass/components/_footer.scss _/
    .l-footer #block-block-36 {
      width: 100%;
      float: right;
      margin-left: 0;
      margin-right: 0;
      clear: none;
      clear: both; }
      /_ line 60, ../sass/components/_footer.scss _/
      .l-footer #block-block-36 img {
        display: inline-block;
        max-height: 35px !important;
        width: auto !important; } }
  @media (min-width: 75em) {
    /_ line 46, ../sass/components/_footer.scss _/
    .l-footer #block-block-36 {
      width: 100%;
      float: right;
      margin-left: 0;
      margin-right: 0;
      clear: none;
      clear: both; }
      /_ line 70, ../sass/components/_footer.scss */
      .l-footer #block-block-36 img {
        display: inline-block;
        max-height: 80px !important;
        width: auto !important; } }

/\* line 1, ../sass/components/_fornt_page.scss */
.l-region--header {
  overflow: hidden;
  *zoom: 1; }

/\* line 6, ../sass/components/_fornt_page.scss */
#block-search-form {
  float: right;
  margin-top: 30px;
  margin-bottom: 30px; }

/\* line 12, ../sass/components/_fornt_page.scss */
#block-lang-dropdown-language {
  float: right;
  margin-bottom: 30px;
  clear: both; }

/\* line 3, ../sass/components/_front_page.scss _/
body.page-αρχική .l-region--header {
  overflow: hidden;
  *zoom: 1; }
/_ line 8, ../sass/components/_front_page.scss _/
body.page-αρχική #block-search-form {
  float: right;
  margin-top: 30px;
  margin-bottom: 30px; }
/_ line 14, ../sass/components/_front_page.scss _/
body.page-αρχική #block-lang-dropdown-language {
  float: right;
  margin-bottom: 30px;
  clear: both; }
@media (min-width: 48em) {
  /_ line 20, ../sass/components/_front_page.scss _/
  body.page-αρχική .pane-clone-of-front-page-panel-pane-1 {
    width: 48.93617%;
    float: left;
    margin-right: -100%;
    margin-left: 0;
    clear: none; } }
@media (min-width: 48em) {
  /_ line 26, ../sass/components/_front_page.scss _/
  body.page-αρχική .pane-popular {
    width: 48.93617%;
    float: right;
    margin-left: 0;
    margin-right: 0;
    clear: none; } }
/_ line 33, ../sass/components/_front_page.scss */
body.page-αρχική .pane-block-11 {
  clear: both; }

/\* line 1, ../sass/components/_header.scss */
.l-region--header {
  overflow: hidden;
  *zoom: 1; }

/\* line 6, ../sass/components/_header.scss */
#block-search-form {
  float: right;
  margin-top: 30px;
  margin-bottom: 30px; }

/\* line 12, ../sass/components/_header.scss _/
#block-lang-dropdown-language {
  float: right;
  margin-bottom: 30px;
  clear: both; }
  /_ line 16, ../sass/components/_header.scss */
  #block-lang-dropdown-language img {
    width: auto;
    height: 20px !important;
    margin-top: 4px; }

/\* line 2, ../sass/components/_main.scss */
body.front .pane-title {
  text-align: center; }

/\* line 8, ../sass/components/_main.scss */
.breadcrumb {
  display: none; }

/\* line 15, ../sass/components/_main.scss */
.l-main li {
  margin-bottom: 10px; }

/\* line 20, ../sass/components/_main.scss */
.floatleftimg {
  float: left;
  padding-right: 20px;
  padding-bottom: 20px; }

/\* line 26, ../sass/components/_main.scss */
.node__links {
  float: right;
  margin-top: 10px;
  margin-bottom: 30px; }

/\* line 1, ../sass/components/_navigation.scss */
.menumyclass,
.tb-megamenu,
.l-region--navigation {
  background-image: url("../images/carbon_fibre.png") !important; }

/\* line 7, ../sass/components/_navigation.scss */
.tb-megamenu {
  background-repeat: none !important;
  color: #aaa; }

/\* line 12, ../sass/components/_navigation.scss */
.tb-megamenu .nav > li > a:focus, .tb-megamenu .nav > li > a:hover {
  background-color: none !important;
  background-image: url("../images/paper.png"); }

/\* line 17, ../sass/components/_navigation.scss */
.tb-megamenu .dropdown-menu li > a:hover, .tb-megamenu .dropdown-menu li > a:focus, .tb-megamenu .dropdown-submenu:hover > a {
  background-image: url("../images/paper.png") !important; }

/\* line 3, ../sass/components/_photo_gallery.scss _/
body.page-photo-gallery .view-bibliography,
body.page-photo-gallery .view-row,
body.page-photo-gallery .views-row,
body.page-photo-gallery .views-row-1,
body.page-photo-gallery .views-row-odd,
body.page-photo-gallery .views-row-even,
body.page-photo-gallery .views-row-first,
body.page-photo-gallery .views-row-last,
body.page-photo-gallery .views-field,
body.page-photo-gallery .views-field-field-image {
  overflow: hidden;
  *zoom: 1; }
/_ line 16, ../sass/components/_photo_gallery.scss _/
body.page-photo-gallery .views-field-title {
  margin-top: 15px;
  margin-bottom: 40px;
  padding-left: 20px;
  padding-right: 20px; }
/_ line 23, ../sass/components/_photo_gallery.scss _/
body.page-photo-gallery img {
  max-height: 600px;
  width: auto; }
@media (min-width: 48em) {
  /_ line 29, ../sass/components/_photo_gallery.scss _/
  body.page-photo-gallery .views-row-odd {
    width: 48.93617%;
    float: left;
    margin-right: -100%;
    margin-left: 0;
    clear: none;
    margin-bottom: 20px;
    text-align: center;
    padding: 20px;
    clear: left; }
  /_ line 37, ../sass/components/_photo_gallery.scss */
  body.page-photo-gallery .views-row-even {
    width: 48.93617%;
    float: right;
    margin-left: 0;
    margin-right: 0;
    clear: none;
    margin-bottom: 20px;
    text-align: center;
    padding: 20px;
    clear: right; } }

/\* line 2, ../sass/components/_youtube.scss _/
body.page-tv .views-row-odd {
  padding-bottom: 20px; }
  @media (min-width: 48em) {
    /_ line 2, ../sass/components/_youtube.scss _/
    body.page-tv .views-row-odd {
      width: 48.93617%;
      float: left;
      margin-right: -100%;
      margin-left: 0;
      clear: none;
      clear: both; } }
/_ line 11, ../sass/components/_youtube.scss _/
body.page-tv .views-row-even {
  padding-bottom: 20px; }
  @media (min-width: 48em) {
    /_ line 11, ../sass/components/_youtube.scss _/
    body.page-tv .views-row-even {
      width: 48.93617%;
      float: right;
      margin-left: 0;
      margin-right: 0;
      clear: none; } }
/_ line 19, ../sass/components/_youtube.scss */
body.page-tv .views-field-title {
  padding-top: 5px; }

/\* line 28, ../sass/components/_youtube.scss */
.iframe-wrapper-out {
  margin: 0 auto;
  max-width: 640px;
  max-height: 480px; }

/\* line 34, ../sass/components/_youtube.scss _/
.youtube-container--responsive,
.iframe-wrapper {
  position: relative;
  padding-bottom: 56.25%;
  /_ 16:9 _/
  padding-top: 25px;
  height: 0; }
  /_ line 41, ../sass/components/_youtube.scss */
  .youtube-container--responsive iframe,
  .iframe-wrapper iframe {
    width: 100% !important;
    height: 100% !important;
    position: absolute;
    top: 0px;
    left: 0px; }

/\* line 27, ../sass/tsini-subtheme.styles.scss */
body {
  background: url("../images/paper.png"); }

/\* line 31, ../sass/tsini-subtheme.styles.scss */
.header-wrapper,
.footer-wrapper {
  background: url("../images/carbon_fibre.png");
  margin: 0 auto;
  clear: both; }

/\* line 38, ../sass/tsini-subtheme.styles.scss */
.footer-wrapper {
  padding-top: 20px;
  padding-bottom: 20px;
  overflow: hidden;
  *zoom: 1; }

/\* line 44, ../sass/tsini-subtheme.styles.scss _/
.l-header,
.l-footer {
  margin: 0 auto;
  padding: 10px; }
  @media (min-width: 48em) {
    /_ line 44, ../sass/tsini-subtheme.styles.scss _/
    .l-header,
    .l-footer {
      width: 48em;
      padding: 0px; } }
  @media (min-width: 75em) {
    /_ line 44, ../sass/tsini-subtheme.styles.scss */
    .l-header,
    .l-footer {
      width: 75em;
      padding: 0px; } }

/\* line 59, ../sass/tsini-subtheme.styles.scss _/
.l-main {
  box-shadow: 0 0 60px rgba(0, 0, 0, 0.15);
  background-color: #FEFCFF;
  margin: 0 auto;
  padding: 20px;
  overflow: hidden;
  *zoom: 1; }
  /_ line 65, ../sass/tsini-subtheme.styles.scss _/
  .l-main li {
    margin-bottom: 10px; }
  @media (min-width: 48em) {
    /_ line 59, ../sass/tsini-subtheme.styles.scss _/
    .l-main {
      width: 48em;
      padding: 60px; } }
  @media (min-width: 75em) {
    /_ line 59, ../sass/tsini-subtheme.styles.scss */
    .l-main {
      width: 75em;
      padding: 60px; } }

/\* line 81, ../sass/tsini-subtheme.styles.scss */
#back-top span#button,
#back-top-prev span#button-prev,
#back-top a, #back-top-prev a {
  display: none; }

@media (min-width: 48em) {
  /\* line 88, ../sass/tsini-subtheme.styles.scss _/
  #back-top span#button,
  #back-top-prev span#button-prev,
  #back-top a, #back-top-prev a {
    display: block; } }
/_ line 98, ../sass/tsini-subtheme.styles.scss _/
.left {
  width: 100%;
  float: right;
  margin-left: 0;
  margin-right: 0;
  clear: none; }
  @media (min-width: 48em) {
    /_ line 98, ../sass/tsini-subtheme.styles.scss */
    .left {
      width: 48.93617%;
      float: left;
      margin-right: -100%;
      margin-left: 0;
      clear: none; } }

/\* line 105, ../sass/tsini-subtheme.styles.scss _/
.right {
  width: 100%;
  float: right;
  margin-left: 0;
  margin-right: 0;
  clear: none; }
  @media (min-width: 48em) {
    /_ line 105, ../sass/tsini-subtheme.styles.scss */
    .right {
      width: 48.93617%;
      float: right;
      margin-left: 0;
      margin-right: 0;
      clear: none; } }

/\* line 112, ../sass/tsini-subtheme.styles.scss */
.floatleftimg {
  float: left;
  padding-right: 20px;
  padding-bottom: 20px; }

/\* line 118, ../sass/tsini-subtheme.styles.scss */
.view_pub_year {
  margin-bottom: 5px; }

/\* line 122, ../sass/tsini-subtheme.styles.scss */
.floatleft {
  font-size: 120%;
  float: left;
  margin: 60px 60px 60px 0px;
  padding: 15px;
  background-image: url("../images/carbon_fibre.png");
  -moz-border-radius: 100px;
  -webkit-border-radius: 100px;
  border-radius: 100px;
  color: white; }

/\* line 133, ../sass/tsini-subtheme.styles.scss */
.floatleft h2, .floatleft h3 {
  color: white;
  font-size: 1.2em; }

/\* line 137, ../sass/tsini-subtheme.styles.scss */
.floatleft a:link {
  font-size: .8em;
  color: white !important;
  -moz-transition: all 0.5s ease;
  -o-transition: all 0.5s ease;
  -webkit-transition: all 0.5s ease;
  transition: all 0.5s ease; }

/\* line 145, ../sass/tsini-subtheme.styles.scss */
.floatleft a:hover {
  color: black !important;
  background: white;
  padding: 1px 1px 1px 0px; }

/\* line 150, ../sass/tsini-subtheme.styles.scss */
.floatleft a:visited {
  color: white; }

/\* line 156, ../sass/tsini-subtheme.styles.scss _/
.node__links {
  float: right;
  margin-top: 10px;
  margin-bottom: 30px;
  clear: both; }
  /_ line 161, ../sass/tsini-subtheme.styles.scss */
  .node__links img {
    height: 25px;
    width: auto;
    margin-top: 6px; }

/\* line 173, ../sass/tsini-subtheme.styles.scss _/
body.page-node-500 .node__links {
  display: none; }
/_ line 179, ../sass/tsini-subtheme.styles.scss _/
body.page-node-500 .field__item p img {
  display: inline-block;
  max-height: 35px !important;
  width: auto !important; }
@media (min-width: 48em) {
  /_ line 177, ../sass/tsini-subtheme.styles.scss _/
  body.page-node-500 .field__item p {
    width: 100%;
    float: right;
    margin-left: 0;
    margin-right: 0;
    clear: none;
    clear: both; }
    /_ line 188, ../sass/tsini-subtheme.styles.scss _/
    body.page-node-500 .field__item p img {
      display: inline-block;
      max-height: 50px !important;
      width: auto !important; } }
@media (min-width: 75em) {
  /_ line 177, ../sass/tsini-subtheme.styles.scss _/
  body.page-node-500 .field__item p {
    width: 100%;
    float: right;
    margin-left: 0;
    margin-right: 0;
    clear: none;
    clear: both; }
    /_ line 198, ../sass/tsini-subtheme.styles.scss */
    body.page-node-500 .field__item p img {
      display: inline-block;
      max-height: 80px !important;
      width: auto !important; } }

/\* line 212, ../sass/tsini-subtheme.styles.scss */
.caption-inner {
  max-width: 100% !important;
  text-align: justify !important;
  line-height: 1.8em !important; }

/*# sourceMappingURL=tsini-subtheme.styles.css.map */

**Comment by replete** [comment]
Thanks for replying. I watched the second video, but it didn't help much. Your code is slightly helpful, but I am one of the 90% that wants to decouple the layout/grid system from component styles.

I want a set of class-based utilities, that I can use in my markup for layout behaviour across breakpoints. This is the approach of popular frameworks like Bootstrap and Zurb Foundation.

Where do I start?

**Comment by Vagelis-Prokopiou** [comment]
1. The official documentation (although I would also prefer it was a little more easy).
2. The videos I provided.
3. This https://www.youtube.com/watch?v=2CM177ldAy8 which breaks down among other things singualitygs and breakpoints.
4. And practicing. Play a little with it and I am sure that you will begin to understand it.
   
   Unfortunately there are not many other resources.

**Comment by replete** [comment]
As an example.

25 seconds after googling 'simple responsive grid scss' I found [gridle](http://gridle.org/), looking at the examples on the homepage, and I know straight away that Gridle can do what I need to.

Anyway, just so frustrating getting up and running with what should be the ultimate grid system approach.

If I get anywhere with it, I'll try and solve the problem myself.

**Comment by finteractive** [comment]
I feel your pain, but you need to focus on what exactly "ultimate grid system approach" means to you. 

Singularity doesn't come pre-baked with a number of assumptions (EG bootstrap / foundation grids have certain default breakpoints, and columns counts). It's harder to learn then other options, because you need to know about grids, make good design calls about them, and then implement them. Singularity  provides a grid system that works in a number of different ways. If that's your goal with then you're in the right place. Basically I like that when giving designers specs, I say "use a grid", and as long as they're decent designers it doesn't really matter what they decide to use as I can create what they design. The alternative is "here's a grid template - Use it!" which is fine as well, but far more limiting to the designer.

Here's some links to sassmeiser for a Sass workshop I ran on singularity. It's designed for people to follow along so just uncomment the sass markup in each exercise to play with each feature of singularity & breakpoint (which I assume you're going to use if you're using singularity). It might be a little tricky without getting talked though it but there's some real, hackable examples to play with.

Break point
Breakpoint Intro - http://sassmeister.com/gist/73a53395a4df14a38aab
no-query support by class - http://sassmeister.com/gist/7b8dded03df82d92970c
No query support by File - http://sassmeister.com/gist/df87e8fe8e5ba8985201

Singualrity
Singularity (No grid - Just default mobile layout) - Setup Mobile First http://sassmeister.com/gist/47e5f7a46938110fca6f
Singularity - 960gs http://sassmeister.com/gist/c0f9776f4a0e3fcc9fc8
Singularity - Non symmetric Grid (comment out the starter example, and uncomment the "After" code block - http://sassmeister.com/gist/861018f358c9c61ea8d1

**Comment by replete** [comment]
@fosterinteractive Thanks for your response.

I build a lot of websites and am trying to move away from heavy frameworks.

Singularity looks amazing because once I understand it, I can create whatever grids I need.

In the meantime however, I just really really needed some basic grid classes ala Zurb or foundation. I couldn't find a straightforward way to do that.

It's hard work un-lazifying the frontend!

**Comment by Vagelis-Prokopiou** [comment]
You may find it paradoxical but gridle seems too complicated for me compared to singularitygs...
Give yourself a little time and I am sure you will never go back...
 In singularitygs you don't have "pre-baked" classes that you add to the html elements.
You just choose the element you want, and span it onto the grid.
Check my code above. See how "@include grid-span" is used. That is the basic mixin you will be using along with the "@include breakpoint", which of course is not a part of singularitygs.

**Comment by Snugug** [comment]
Singularity is designed not as a grid system like the CSS Systems we've unfortunately grown accustom to (like Bootstrap and Foundation). Instead, it's a framework in its truest sense: meant to have custom input and produce custom output, not use as the whole it's delivered as. Singularity's design philosophy is giving a user the tools they need to create the grid of their dreams, not giving them a grid to drop in place. If that's what you're looking to do, you can _create_ one with Singularity, but it's not provided out of the box.

Because of these needs, Singularity has a slightly different mental model than other frameworks or systems. It supports multiple different output systems (`float` like Susy, Bootstrap, or 960gs, `isolation` like Zen Grids, and `calc` which is like `isolation` but allows for mixed fixed and fluid grids, plus a full plugin system to allow a user to make custom output systems and example custom input syntaxes for working in the different mental models of each output system) and not just symmetric grids, but asymmetric grids as well. It allows users to choose whether they want fixed or fluid gutters. Breakpoints can be custom-defined to your content (which we prefer to device based breakpoints, but that doesn't stop someone from doing that), and grids, gutters, and gutter styles can break at different points based on design needs; they don't always need to break together. The math done is always based on a theoretical 100% container as opposed to final desktop grid dimensions, meaning that grid nesting, combining different symmetric and asymmetric grids, and even grid styles, all works in a much more web-first way.

All of this deep level of customization means that it's impractical for us to provide things like grid classes or generally make the assumptions that other grid systems make. Is it the right solution for everyone? Absolutely not. But for those who want that power, not much else comes close. I agree the documentation needs help, we're working on a total overhaul of the site, but rewriting the documentation from scratch is a hard and long task. In the meantime, we've got a [Quickstart Guide](https://github.com/at-import/Singularity#singularity-quickstart) and our [wiki](https://github.com/at-import/Singularity/wiki) provides full technical documentation. We'll absolutely make sure that as part of documentation refresh we include some basic examples as well.
