### ISSUE TITLE
Equal Columns in a Grid

### ISSUE THREAD

**Issue by iaakash** [at-import/Singularity#216]
Is there any way to achieve Equal Height Columns in a row using Singularity?

**Comment by scottkellum** [comment]
Hi @iaakash,

Short answer no

Long answer yes, you can write a custom output mode to support this via flexbox or whatever. Here is a custom output mode for calc: https://github.com/at-import/Singularity-extras/blob/1.x.x/stylesheets/singularity-extras/outputs/_calc.scss

**Comment by Snugug** [comment]
As Scott said. No.
