### ISSUE TITLE
Website Down?

### ISSUE THREAD

**Issue by patrickcate** [at-import/Singularity#235]
The Signularity website at: http://singularity.gs seems to be down.

**Comment by Vagelis-Prokopiou** [comment]
Unfortunately, there is hardly any activity on this grid system any more, in general. I wonder if it is "dead". Too bad if that is true.

**Comment by scottkellum** [comment]
Yeah it’s down, all documentation is on github and I’m not going to continue to pay for the domain. @Snugug has been keeping this project on life support, but you’re right, not much is going on. Susy 2 has a lot of the features from Singularity and I stopped using grid frameworks in general a long time ago.

**Comment by Vagelis-Prokopiou** [comment]
Thanx for the answer @scottkellum. I understand. You are right.
Just a small clarification if you wish.
You said "I stopped using grid frameworks in general a long time ago". And you replaced them with what? Bootstrap? I am just curious if there is a new trend or best practice that I am not aware of.
Anyway, thanx again for all your work on this grid system.

**Comment by Snugug** [comment]
Modern CSS is mostly powerful enough that they aren't needed. I consider Singularity stable and mostly feature complete, so there isn't much active development on it. When Sass 4 comes out there will be an update to support the new module system. About once a quarter I get around to going through the issue queue.

**Comment by Vagelis-Prokopiou** [comment]
Thanx @Snugug.

**Comment by scottkellum** [comment]
@Vaggos yup what @Snugug said. CSS these days (flexbox and I still like floats sometimes) makes things fairly simple and I find I have more control when my layout stuff isn’t abstracted too far away.

I also don’t put much stock into best practices. Do what works best for you and your project goals.

**Comment by Vagelis-Prokopiou** [comment]
Thank you @scottkellum. Got it.
In either case, thank both you and @Snugug for all your hard work on this project. I really appreciate it.
