### ISSUE TITLE
All sub-pages of the installation page are identical

### ISSUE THREAD

**Issue by tom-sift** [at-import/Singularity#236]
In the documentation for installation: https://github.com/at-import/Singularity/wiki/Installation all pages in the right hand nav below 'Installation':

* https://github.com/Team-Sass/Singularity/wiki/Installation#creating-a-new-project-with-singularity
* https://github.com/Team-Sass/Singularity/wiki/Installation#using-with-an-existing-project
* https://github.com/Team-Sass/Singularity/wiki/Installation#legacy-internet-explorer-support
* https://github.com/at-import/Singularity/wiki/Installation#singularity-demos

Are all the same installation page.

Cheers

Tom

**Comment by Snugug** [comment]
Updated
