### ISSUE TITLE
Padding?

### ISSUE THREAD

**Issue by Snugug** [at-import/Singularity#25]
What is the purpose of specifying padding as part of the grid definition? Is was my assumption that that's what the gutters were for, and if additional padding was needed, a per-element padding would be added. Is it to help with calculations of widths? If so, thoughts on using border-box and not having this issue? Just a little confused as to the thinking here.

**Comment by scottkellum** [comment]
Already uses border-box and asymmetric padding is included with the column width list so it is easier to keep track of what padding is going with what column.

I really like having padding tied to the grid. It keeps the text lined up nicely. You could of coarse write your own. For people who want fixed-width gutters, padding presents a good option for that as well.

**Comment by Snugug** [comment]
Interesting, okay. Sorry for the onslaught of issues, trying to fully grok Singularity so I'm better prepared to recommend it/contribute.

**Comment by scottkellum** [comment]
It’s cool, enjoy the help :)
