### ISSUE TITLE
page margins/wrapper

### ISSUE THREAD

**Issue by Snugug** [at-import/Singularity#26]
Most designs that I'm aware of don't but up right against the edges of the screen and instead have some sort of edge gutter, but singularity doesn't have this concept. Thoughts on adding it in?

**Comment by scottkellum** [comment]
Lets call them page margins instead of gutter edge.

I always define these with the page wrapper or body element. I really enjoy the flexibility of writing my own wrapper depending on the context of a project so I never felt the need for one in Singularity.

**Comment by Snugug** [comment]
Page Margins, done.

I think it may be a good idea (and this is tied the other issue I presented about container mixin) to provide a way for users to set some variables and get a container with page margins et all much like they do for Susy. Sure, we can all write our own, but if we think a more broad usecase then I think people would want a container.

Once Mason comes up for air and we can get Breakpoint Contexts merged in and a gem pushed, I think my madness will become less mad.

**Comment by scottkellum** [comment]
I really don’t like Susy behavior for this. I would rather have wrapper stuff separated from the grid mixin. But yeah, wrapper code is simple enough.

**Comment by scottkellum** [comment]
Merge with to issue #21
