### ISSUE TITLE
inline-table

### ISSUE THREAD

**Issue by scottkellum** [at-import/Singularity#28]
Check out inline-table on columns. They might be more flexible and widths calculated with fewer rounding errors. Also no need for floats. Another advantage is that all elements in a row will be equal height, no need to clear anything in new columns. Trivial to center-align content by must using `display: table-cell;`.

Watch out for white space messing with layout as inline elements tend to have stray spaces.

**Comment by Snugug** [comment]
Interesting… I'll take a look at this while futzing with the codebase.

**Comment by Snugug** [comment]
I'm going to close this as we've closed the Issue 32 which superseded this.

**Comment by scottkellum** [comment]
reopened. I want to work on this to get the output API in nice working order. No pressure as #32 is incredible.

**Comment by Snugug** [comment]
Agreed, and ok!

**Comment by scottkellum** [comment]
Not a 1.0 priority. back burner for now, unless you feel motivated/inspired.

**Comment by Snugug** [comment]
No. No I do not. :tongue:

**Comment by scottkellum** [comment]
Apparently that is an emoji tongue. It is frightening.

**Comment by Snugug** [comment]
I know, right?! I don't know when, and I don't know why, but GitHub has added Emoji to their commenting! 

If you :mouse: a :cookie:…

**Comment by scottkellum** [comment]
Not in scope for core
