### ISSUE TITLE
Test in IE

### ISSUE THREAD

**Issue by scottkellum** [at-import/Singularity#29]
Lots of testing needed, especially in IE. Probably not too many issues but should test.

**Comment by Snugug** [comment]
Yes. Yes it does.

**Comment by Snugug** [comment]
I think, for the most part, we should be good. Percentage width IIRC are always going to be an issue in IE, but with the [box-sizing: border-box polyfill](http://singularity.gs/#install) in place, I think we're good.

**Comment by scottkellum** [comment]
Meh, I feel like we have this covered for now.
