### ISSUE TITLE
zen-grid style rounding isolation

### ISSUE THREAD

**Issue by scottkellum** [at-import/Singularity#32]
If the `display: inline-table;` stuff in #28 doesn’t flex nicely look into this method to reduce rounding errors by @JohnAlbin in zen grids: http://palantir.net/blog/responsive-design-s-dirty-little-secret

**Comment by scottkellum** [comment]
Implemented in this branch: https://github.com/scottkellum/Singularity/tree/column-isolation

Still need to add rtl/ltr support back in.

Also broke down into structure that allows multiple styles of grids. Easy to swap float columns for newer methods like table-cell/inline-table.

**Comment by scottkellum** [comment]
RTL added in b7e6d8458f96ac1af8e4b85983228ab86a786a69

**Comment by scottkellum** [comment]
Cleanup shared styles: fb863c4c4ca01b69caeace5b6b8b90bafcde95d3

Buggy as hell but feature complete.

**Comment by Snugug** [comment]
So, IIRC, while Zen Grid's rounding isolation solves the current issue in Safari well (no longer an issue in Chrome or at least won't be soon, never an issue in FF), it does present us with a new problem; specifically that if you want padding _and_ margin, you need to wrap your columns in wrapper divs, which is something I never particularly liked the idea of for a grid system (especially a semantic one), as it then forces HTML styling on an end user. Some of this can be sorted out with `calc()` but the [support isn't there yet on mobile](http://caniuse.com/calc).

Also, if you'll let me paraphrase Ethan's response to this article: "Yes, rounding errors are an issue, but never really to the extent described in practice". To which John replied it was a little bit of linkbait.

There's one other thing we could look into that I particularly like, and that's how Susy handles it: namely, they leave it to the browser to handle but reduce the likelihood of you seeing it by floating the last item in the row off to the opposite direction (right for ltr, left for rtl).

All this said, I'll take a look at this when in Munich and maybe I'm totally off base and this will be awesomesauce.

**Comment by scottkellum** [comment]
There are some other advantages to it. It works like absolute positioning in that each column can be displayed in any order regardless of markup order but uses floats so the height can be cleared . The issue should just be with clearing floats. Padding should work as it did before.

**Comment by JohnAlbin** [comment]
> specifically that if you want padding and margin, you need to wrap your columns in wrapper divs

I clarified this on twitter, but it bears repeating. It's Zen Grids that doesn't (yet) have an interface for margins between columns. But the underlying CSS method can use margins between columns and it does not require wrapping divs.

**Comment by Snugug** [comment]
Yup, thank you.
The no margin wrapper div was exactly what I was thinking of, but again, thank you for clarifying, relieves my worries.
I've got some time now so I'm going to take a look at this @scottkellum. What exactly is being wonky?

**Comment by Snugug** [comment]
Hmm, this solution is providing some awkward results.

Previously, we could do something like the following:

``` scss
$columns: 1, 2, 3;

#div1 {
  @include grid-span(1);
}

#div2 {
  @include grid-span(1);
}

#div3 {
  @include grid-span(2, 2);
}
```

And previously, what you'd get is one row with two columns and a second rwo with one column spanning the last two widths floated to the right. Now, that same code not only won't create the second row, it will hide `#div2` behind `#div3` on the first row, and we can't use the standard `clear: left;` and `clear: right;` which is how we'd clear them previously. Not even a classic CSS clearfix will fix this.

@JohnAlbin How did you get around the clearing issue in ZG?

**Comment by scottkellum** [comment]
Zen clearing:
https://github.com/JohnAlbin/compass-zen-grids/blob/master/stylesheets/zen/_grids.scss#L168
and
https://github.com/JohnAlbin/compass-zen-grids/blob/master/stylesheets/zen/_grids.scss#L40

Not difficult, just want to make this smarter simple. We could auto clear when reaching the end of a row but I want this to be more flexible than that. Zen has some advantages that columns don’t have to be in order or span to the end of the row so clears might have to happen in a different order.

Could easily add an omega or clear function, or require a wrapper on a row but all of these options add more complexity. This might be necessary though.

**Comment by Snugug** [comment]
Hmm, thought I had added those clears in when I was testing and they didn't work. I'll try again.

For me, here's my preference for clearing:
1. Auto clear each column
2. Clear the last column automatically
3. Clear function to allow for clearing when you like
4. Anything that requires users to change their markup.

**Comment by Snugug** [comment]
I think I've figured out clearing, and I'm going to write a little bit to make this all work. This also appears to take care of pull/push for this grid system.

Next up, I think vertical rhythm!

**Comment by Snugug** [comment]
Awesome, so I've added clearing stuff, let me know what you think.

The Zen ISO html/css is my test for the clearing stuff. I have noticed, however, that the second row's width isn't calculated correctly and/or the position of `grid-span(1, 4)` is positioned wrong. Thoughts on what's up with that?

**Comment by scottkellum** [comment]
Pushed a few float fixes. trying to isolate this rounding bug. I suspect bug #23 witch is proving to be really annoying to find.

**Comment by Snugug** [comment]
I'll work on this a bit on my flight out tomorrow, and if I've got some free time in Munich I'll do that as well.
