### ISSUE TITLE
Clean Up Singularity Example

### ISSUE THREAD

**Issue by Snugug** [at-import/Singularity#34]
I just ran into this issue when trying to create a test example. In our Examples config.rb file, it's loading Scott's local Singularity framework which no one else is going to have. I think we need to clean this up so that all of our examples are loading off of the stylesheets dir that we have in the branch, specifically:

```
@import '../../stylesheets/singularitygs';
```

This will make it so that any of us can run and build examples easily, off of our own boxes, and off of the current version of singularity in the branch we're on.

**Comment by micahgodbolt** [comment]
Is this still an issue. I just set up a test page in the example directory and everything compiled properly, and the css connected just fine.

**Comment by Snugug** [comment]
No, it's done already.
