### ISSUE TITLE
Add Push/Pull Functions

### ISSUE THREAD

**Issue by Snugug** [at-import/Singularity#35]
We need to be able to push/pull around the grid.

**Comment by scottkellum** [comment]
Doesn’t #32 make this unnecessary?

**Comment by Snugug** [comment]
I'm not 100% sure that it will. I'd be in favor of leaving this open until we're sure it does, but if we're including other methods of grid creation, we may still need this.

**Comment by Snugug** [comment]
So yah, like you said, this isn't needed with Zen style.
