### ISSUE TITLE
Identify “standard use case”

### ISSUE THREAD

**Issue by scottkellum** [at-import/Singularity#38]
Singularity can do a lot, a hell of a lot witch introduces a learning curve to new users. We need to identify a standard use case to recommend and present as the way to do things. Of coarse other stuff should be documented but holding one thing up will give people one point of introduction.

**Comment by Snugug** [comment]
I believe the standard use case for Singularity should be non-symmetric grids as many of the design decisions we've made for Singularity are based around supporting that, some of which preclude common usage patterns for purly symmetric grid systems.

**Comment by scottkellum** [comment]
closing, I think we have consensus on standard and advanced use patterns.
