### ISSUE TITLE
Objects & mixin consistanty

### ISSUE THREAD

**Issue by scottkellum** [at-import/Singularity#39]
objects and mixins use different language for how they fit on the grid. I have no idea what I was smoking when making that happen but extendable classes/% need to follow the same naming conventions as mixins.

**Comment by Snugug** [comment]
Presumably something good. I'll take a look.

**Comment by micahgodbolt** [comment]
@scottkellum are you talking about objects starting at 0 (.a0-2) and mixins starting at 1 (@include grid-span(1,3)), or are you talking about something else?

**Comment by scottkellum** [comment]
mixins: first number is the column something starts and the second is how many columns the element spans
Objects: counts gutters not columns from starting edge to final edge.

**Comment by micahgodbolt** [comment]
Ok, this makes sense now.

Currently the following describe the same thing, a 3 column span, starting at the 1st position

``` css
@extend .a0-2
@include grid-span(3,1)
```

So we need to change the extend to follow the mixin

``` css
@extend .a3-1
```

**Comment by scottkellum** [comment]
bingo

**Comment by micahgodbolt** [comment]
hey @scottkellum i updated the branch with a new grid-objects mixin. Care to check it out? It's a change to the way people will need to write their extends, so I wanted to make sure we've got it right.

**Comment by scottkellum** [comment]
Marked that it needs QA. Looks done but saving for final checks.

**Comment by Snugug** [comment]
Is this in master yet?

**Comment by scottkellum** [comment]
yes: https://github.com/scottkellum/Singularity/pull/56

**Comment by Snugug** [comment]
Awesome, just making sure it's in the 1.0 prerelease
