### ISSUE TITLE
background-grid

### ISSUE THREAD

**Issue by scottkellum** [at-import/Singularity#41]
background grid still requires % gutters.

**Comment by Snugug** [comment]
Once my computer is back online I'll work on it.  

~ Sam Richard
http://snug.ug

**Comment by scottkellum** [comment]
Might be more pressing/fun issues to work on. Prioritize as you see fit.

**Comment by Snugug** [comment]
Will do. Computer out of commission for the moment  

~ Sam Richard
http://snug.ug

**Comment by Snugug** [comment]
I'm on it.

**Comment by Snugug** [comment]
https://github.com/scottkellum/Singularity/pull/42. Fixed.
