### ISSUE TITLE
Gridset or grids

### ISSUE THREAD

**Issue by scottkellum** [at-import/Singularity#43]
Any reason why $grids is not an appropriate variable? Short, simple, easily typed and simply the plural of $grid.

Also distancing Singularity from gridset might be a good idea. Not that we should go out of our way to do so but this is an easy area to avoid confusion.

**Comment by Snugug** [comment]
I'm cool with it. The gridset semantics made sense to me outside of gridset app context, but grids works just as well.

~ Sam Richard
http://snug.ug

**Comment by Snugug** [comment]
Closing this, rolling this into the integration as part of [#22](https://github.com/scottkellum/Singularity/issues/22)
