### ISSUE TITLE
Import not found (singularitygs/helpers)

### ISSUE THREAD

**Issue by lmartins** [at-import/Singularity#47]
Im getting this error while compiling using the latest version (singularitygs 0.0.13):

 error main.scss (Line 34 of _singularitygs.scss: File to import not found or unreadable: singularitygs/helpers.
Load paths:
  /Users/luismartins/Sites/LAB/singularity/css-src
  /Library/Ruby/Gems/1.8/gems/compass-0.12.2/frameworks/blueprint/stylesheets
  /Library/Ruby/Gems/1.8/gems/compass-0.12.2/frameworks/compass/stylesheets
  /Library/Ruby/Gems/1.8/gems/compass-rgbapng-0.1.1/lib/stylesheets
  /Library/Ruby/Gems/1.8/gems/bootstrap-sass-2.1.0.0/vendor/assets/stylesheets
  /Library/Ruby/Gems/1.8/gems/sassy-math-1.2/stylesheets
  /Library/Ruby/Gems/1.8/gems/modular-scale-1.0.2/stylesheets
  /Library/Ruby/Gems/1.8/gems/breakpoint-1.3/stylesheets
  /Library/Ruby/Gems/1.8/gems/singularitygs-0.0.13/stylesheets
  Compass::SpriteImporter)
overwrite main.css

**Comment by lyleunderwood** [comment]
I was getting this same error, I'm now pointing at master and it appears to be resolved.

**Comment by Snugug** [comment]
I may have built from the wrong branch. I'll double check and reroll the gem.

**Comment by lmartins** [comment]
Since i've reported this issue i've noticed my gem didn't include all css files on it's library. I've put them manually and now it compiles.

**Comment by Snugug** [comment]
Like I said, I may have built the gem of of the wrong branch. Will be fixed

**Comment by lmartins** [comment]
Sure, just wanted to make sure I provided all the info I could.

**Comment by Snugug** [comment]
Was an issue in the gemspec. Fixed, pushed new gem.
