### ISSUE TITLE
Make Grid Span Function Compatible with Grids and Grid Span Mixin

### ISSUE THREAD

**Issue by Snugug** [at-import/Singularity#52]
Above

**Comment by micahgodbolt** [comment]
So the grid span function returns a column-span using it's given attributes. We could let grid-span accept multiple sets of attributes along with breakpoints, and then walk through them creating all of the media queries. Similar to grid-objects. It would certainly make sense to have a similar syntax for the function and object.

Am I understanding this issue correctly?

**Comment by Snugug** [comment]
There are a bunch of functions that need to be updated to to work with `$grids`, so I'm going to do a bit of refactoring today to get that to work.

**Comment by scottkellum** [comment]
FYI, doing a lot of restructuring in my branch: https://github.com/scottkellum/Singularity/tree/grid-output-api

mostly breaking things down into separate files.

**Comment by scottkellum** [comment]
Also, I really love the logic you set up for this, possibly break this into a separate function that returns nth($grids, 1)?

Maybe structured like this? that way it can be easily injected into other functions/mixins?

``` scss
@function find-grid() {
  @if $length > 0 {
    @return nth($grids, 1);
  @else {
    @return $columns;
  }
}
```

**Comment by Snugug** [comment]
Yah, I was going to spend some time today breaking the logic in grid-span into find-columns, find-gutter, and find-padding.

**Comment by Snugug** [comment]
Closing this as I'm about to push the update to make this work!
