### ISSUE TITLE
Make Grid Objects work with Responsive Grids

### ISSUE THREAD

**Issue by Snugug** [at-import/Singularity#53]
As Above

**Comment by micahgodbolt** [comment]
So we want to make the grid objects work with defined breakpoints, is that our goal? I would just call a different mixin per breakpoint in my .scss. Do you want theses breakpoints built into the mixin somehow?

**Comment by Snugug** [comment]
Hmm, that's actually a good question. How _do_ we want grid objects to work in relation to the multiple grids option?

Either way, the answer is we don't want it to work with our predfined breakpoints, but rather breakpoints and grids as defined in the `$grids` variable.

**Comment by micahgodbolt** [comment]
Oh, this shows how out of the loop I am. So you already have breakpoints written in to singularity. That all makes a bit more sense. Trying to grok the entire process can take quite a bit of coffee on a monday.

**Comment by Snugug** [comment]
:P fair enough.

I've just updated the [Singularity website](http://singularity.gs/) with the most up-to-date documentation on the project. Check out the Advanced section to see how Singularity handles responsive grids.

**Comment by micahgodbolt** [comment]
So at this point the grid-object creates a series of classes/id's/silents with a prefix and a number to start and number to end (a1-2, a2-10, a10-12). I don't think it'll be possible to assume how the user wants this to change when going from 12 to 3 columns (could be 3 equal columns, all full width, or a mix). So we need to create a method for the user to designate the layout for each breakpoint.

So intstead of writing 

``` css
.container1 {
@extend %a1-2;
}
```

we'll need something like 

``` css
.container1 {
  @include layout-set(a1-2, a1-1); 
 /*silent extenders for each breakpoint written in $grids variable */
}
```

I don't think it'll be possible to create a system for static classes as you might have one div using .a1-2 that you want to be .a1-3, and a different .a1-2 that turns into .a1-1

Thoughts?

**Comment by Snugug** [comment]
That's quite possible. @scottkellum, thoughts?

**Comment by scottkellum** [comment]
Brilliant, do it.

**Comment by Snugug** [comment]
So, I just re-read this, and let's not do this. This, upon second glance, seems like it's essentially the standard grid-span function, but with selector names instead of the span/location, which I don't like because it's abstraction for abstraction sake and appears to break the mental model for which the grid objects were created in the first place.

I think what I'd prefer to see is each grid set build out its objects independently as you would expect, with predictable prefixes (set1-a1-2, set2-a3-4, etc…), have the media queries for the sets above 1 inside the selector themselves (so we can reliably extend them), and instruct users who want to use grid objects to `@extend` whatever objects they'd like. This methodology, IMO, more closely follows both the mental model of grid objects in general (piling on classes) and prepares them for the mental model of moving to normal Singularity usage (be sure to include the changes, or else you'll break your grid).

I'm going to be flying today, so I should have a fair chunk of time to work on this and hopefully knock this out.

**Comment by scottkellum** [comment]
re-labeling. Definitely think this can wait until 1.1 or later.

**Comment by Snugug** [comment]
If so, I'm going to make a final pass over the codebase, then would you like to push the 1.0 or should I?

**Comment by scottkellum** [comment]
bump to 0.9 beta for now. I want to hammer at docs and test the shit out of this before 1.0. I should have time this week to do so.

**Comment by Snugug** [comment]
Sounds good, will do.
