### ISSUE TITLE
Push/Pull

### ISSUE THREAD

**Issue by Snugug** [at-import/Singularity#62]
With the traditional Float style output, we now need to include a way to pull/push columns.

**Comment by Snugug** [comment]
Done and done.

**Comment by OnkelTem** [comment]
How this is done?? How to make pull/push??? Documentation doesn't help!

**Comment by lolmaus** [comment]
Push/pull has been deprecated in favor of the isolation output style which does not require push/pull at all.

Here's some details on using push/pull, though it might be obsolete for the recent version of Singularity: https://github.com/Team-Sass/Singularity/issues/161#issuecomment-31629221

**Comment by OnkelTem** [comment]
Oh, thanks
