### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by Snugug** [at-import/Singularity#64]
While probably not a blocker for a 1.0 release, we seriously need to update the documentation for Singularity as it can do so frickin much right now that I don't even think I know all of the nooks and crannies of the system. At the least for the 1.0 release, we need to document Grid Output API and then work on a cleanup.

**Comment by scottkellum** [comment]
We do need to update standard use documentation for 1.0. Agree, API stuff isn’t a blocker but we need to get a game plan for it before 1.0.

**Comment by Snugug** [comment]
I'm going to do a bunch of tests on creating custom grid output styles so we can doc those up.

**Comment by scottkellum** [comment]
Cool, I am going to figure a site relaunch to support better docs.

**Comment by scottkellum** [comment]
Wireframed: http://tmp.pgdn.us/singularity-wireframe.pdf

**Comment by Snugug** [comment]
We got docs!
