### ISSUE TITLE
Rewrite in Ruby

### ISSUE THREAD

**Issue by Snugug** [at-import/Singularity#65]
I know this is a little premature, but I can see that the complexity of Singularity is starting to affect compile performance, so we should probably rewrite this in Ruby. This is most definitely blocked on https://github.com/nex3/sass/pull/310

**Comment by scottkellum** [comment]
+1, we can probably create a sass level function to pass variables to a ruby level function. Curious as to what exactly is hurting performance so much, might be able to audit and streamline Sass first.

**Comment by Snugug** [comment]
Well I know one thing that's an issue is we need to do the full grid looping for the `find-grid`, `find-gutter`, and `find-padding` functions which gets called a few times. I try and mitigate the need for doing the whole loop as best as possible, but most of the time a fairly large loop is going to run for each of them.

**Comment by scottkellum** [comment]
@Snugug re-wrote everything, not in ruby. Yay @Snugug!
