### ISSUE TITLE
duped styles from shared and per-column

### ISSUE THREAD

**Issue by scottkellum** [at-import/Singularity#69]
Here: https://gist.github.com/4051541

these lines should not be written on `.a1-1`:

``` css
  overflow: hidden;
  *zoom: 1;
```

from: https://github.com/scottkellum/Singularity/blob/master/example/sass/oocss-variable-padding.scss#L15

I tried removing this: https://github.com/scottkellum/Singularity/blob/master/example/sass/oocss-variable-padding.scss#L15

and all instances for that matter, but for some reason it kept compiling with *zoom: 1 there. Driving me nuts.

**Comment by micahgodbolt** [comment]
Is zoom 1 part of a clear fix?

**Comment by Snugug** [comment]
*zoom: 1 is Clearfix IE stuff

**Comment by robwierzbowski** [comment]
I'll fix this in https://github.com/scottkellum/Singularity/issues/78, as long as I'm in there.

**Comment by scottkellum** [comment]
Worrying less and less about this after seeing how gzip squashes repeated code.

**Comment by robwierzbowski** [comment]
Simple fix, already done. Clearfix was being applied in the float/isolation-clear mixins, and pseudo clearfix code was being applied in float/isolation-common mixins. I switched it to actual clearfix only in common.

**Comment by robwierzbowski** [comment]
Fixed in the above merge.
