### ISSUE TITLE
Remove Padding?

### ISSUE THREAD

**Issue by Snugug** [at-import/Singularity#73]
It just occurred to me that, while `$padding` is very useful of you're only dealing with outer columns, the moment you start to nest columns it becomes a hassle as the padding will start to stack.
Take, for instance, 
`$columns: 2, 6, 2
$padding: 12px`. 
Say I now have, inside the 6, `+grid-span(4, 1, 6)`. That will get `12px` padding as well, resulting in a total left padding of `24px`. This either leads a user to need to specify that they want no padding for each and every nested grid or we should drop padding  as the current padding model, while working as designed, breaks IMO the standard mental model.
The other option is to have a check in `grid-span` to see if the grid being used is equal to the grid that naturally be used and if not, not include padding unless one is specifically passed in, but that's fragile at best.

Thoughts?

**Comment by micahgodbolt** [comment]
Seems like it might be easiest to provide the padding setting in the columns mixin. 

Looks like you can currently do 

``` css
$columns: 1, 1 12px, 1;
```

How about changing it to allow for this

``` css
$columns: 1, 1, 1, 12px;  /* 12px padding on all 3 columns */
```

Not sure how you'd differentiate that variable from others, but this way you could keep the padding scoped to this particular grid.

**Comment by Snugug** [comment]
That solution seems to add more issues than it solves to me, but more importantly, doesn't solve the issue inherit in this problem. Namely, the issues are "how do we choose which padding takes precedence when two different paddings can be passed in in `grid-span`", "how do we handle compounding padding, what should we assume the user wants", and "how do we deal with spans that have different paddings depending on the columns they span".

**Comment by micahgodbolt** [comment]
What is the 6 inside of +grid-span(4, 1, 6)? I presume that is new, as it's not in the documentation on the site.

**Comment by scottkellum** [comment]
done
