### ISSUE TITLE
Undefined mixin 'structure-common'

### ISSUE THREAD

**Issue by philsinatra** [at-import/Singularity#76]
Setting up a new project, I put in the default values for a 12 column grid, same as on the website. 
When I use the 'grid-object' mixin I receive an error:

SCSS: @include grid-objects($selector: ".");

Error: Line 9 of _grid-objects.scss: Undefined mixin 'structure-common'.

**Comment by scottkellum** [comment]
Thanks, yeah we have been making some changes to the output API and things are a little shaky here at the moment. Will dig in when I find some time.

**Comment by philsinatra** [comment]
Do you have a copy of the grid-objects output I can use temporarily? I am mid project and I don't want to switch grid systems. I can deal with the basic 12 column grid until the fix is complete.

**Comment by scottkellum** [comment]
sudo gem uninstall singularitygs
sudo gem install singularitygs -v 1.0.alpha.0

That should do it. Here are the versions you can roll back to: http://rubygems.org/gems/singularitygs/versions

**Comment by philsinatra** [comment]
Is this issue still active in your debugging or should I consider it dead for now?

**Comment by scottkellum** [comment]
Closing, didn’t realize this was still open.

Major re-write for 1.0. We don’t actually have grid-objects anymore in core.

**Comment by Snugug** [comment]
If you'd still like to see Grid Objects, please either file an issue with [Singularity Extras](https://github.com/Team-Sass/Singularity-extras) or write an extension and issue a pull request for us to add it to the list of Singularity Extensions!

**Comment by philsinatra** [comment]
Will do. Thanks guys.
