### ISSUE TITLE
Configurable border box and clearfix inclusion.

### ISSUE THREAD

**Issue by robwierzbowski** [at-import/Singularity#78]
Two parts to this issue:

`Border-box`: For those of us who are applying `border-box` with the universal selector, it's unnecessary to add it with every grid-span() include. A configuration option would be nice.

Clearfix: I'm assuming the `zoom` and `overflow: hidden` applied with each grid-span() are for clearfix. `Overflow: hidden` is a problem if you're positioning elements within a column outside of the column, but I understand some people prefer using it so they can add `::before` and `::after` on their clearfixed containers. Do you think it would be possible to add a configuration option that allows you to specify which clearfix you'd like to use? If the config option could take mixins (which might be impossible in sass) a user could use any of the standard compass clearfix mixins or their own. 

I'm going to work on these over the course of my current project, but I just started using singularity so any feedback (this is completely impossible, we're using those properties for something besides clearfix, you've gone crazy mad with power lust) would be appreciated.

**Comment by Snugug** [comment]
I was thinking about just this issue over the weekend and agree it's something we can do better. If you get some code written, that'd be great as I don't have time to work on it right now, but if not when I do have time I'll take a crack at it.

**Comment by robwierzbowski** [comment]
Cool. After looking a little closer I see you're using a generated pseudoelement clearfix (my favorite, the necolas table version) along with `overflow: hidden`. I'll see if I can figure out exactly why that is and then take a shot at some config options.

**Comment by Snugug** [comment]
I honestly don't remember why we're overflow: hidden-ining our clear fixes. Scott, you remember why?

**Comment by scottkellum** [comment]
nope, lets kill it.

**Comment by robwierzbowski** [comment]
Question before I finish this up: in [_container.scss](https://github.com/scottkellum/Singularity/blob/master/stylesheets/singularitygs/mixins/_container.scss#L57) there's a test for legacy ie flags and an expression. The flags and css rule aren't included anywhere else clearfixes are used. 

Is this necessary? I was under the impression `zoom: 1;` worked well on its own for the old ie's.

**Comment by robwierzbowski** [comment]
Anyone who wants more info on the expression: http://nicolasgallagher.com/better-float-containment-in-ie/

Should this be here by default, or  should we let people add it on their own with the new configurable clearfix?

**Comment by scottkellum** [comment]
Looks awesome, lets play with it as default behavior and see how it goes.

**Comment by robwierzbowski** [comment]
Here you go: https://github.com/scottkellum/Singularity/pull/79

**Comment by robwierzbowski** [comment]
Ah sorry, misread your last comment. If you want to add it back in, I would put it after `@include pie-clearfix()` in `_clearfix.scss`.

**Comment by Snugug** [comment]
You rock sir. Will look at this in a bit

**Comment by robwierzbowski** [comment]
Fixed with https://github.com/scottkellum/Singularity/commit/84a19fdf32d8c275e186535ddc3a43e1ffa9aa2a.
