### ISSUE TITLE
Use Toolkit's Clearfix

### ISSUE THREAD

**Issue by Snugug** [at-import/Singularity#82]
I really hate Compass's Clearfix mixin; that's where overflow: hidden is coming from and has a lot of potentially unnecessary stuff in it. Can we either require Toolkit and import its clearfix partial to use those or rewrite them into Singularity?

**Comment by scottkellum** [comment]
good question. hmm, toolkit is pretty heavy with dependencies already including singularity. Maybe just re-write something small like that into Singularity for now?

**Comment by Snugug** [comment]
Let's rewrite it. Circular dependencies may make heads splode

**Comment by robwierzbowski** [comment]
Believe I fixed this when making the clearfix mixin configurable. Right now singularity should be using the compass `pie-clearfix` (which I don't think uses overflow hidden), plus the legacy-edge-case zoom expression everywhere clearfix is needed (if I didn't miss anything).

Clearfix code: https://github.com/scottkellum/Singularity/blob/master/stylesheets/singularitygs/mixins/_clearfix.scss#L4
Merged pull request: https://github.com/scottkellum/Singularity/pull/79
Instructions on overriding: https://github.com/scottkellum/Singularity/blob/master/stylesheets/_singularitygs.scss#L44

**Comment by scottkellum** [comment]
Still an issue?

**Comment by Snugug** [comment]
It's in! Let's close this!
