### ISSUE TITLE
Problem installing singularity into an existing compass project

### ISSUE THREAD

**Issue by heedfull** [at-import/Singularity#83]
Trying to install singularity into an existing compass project.

when i run
`$ compass install -r singularitygs -f singularitygs`

i get `Error: ambiguous option: -f`

so I removed the -f and the sigularitygs from the end no I get this error

`Error: parse error: Please specify a pattern.`

Any help greatly appreciated, unfortunately I need to support <IE8

p.s. I'm using a mac

**Comment by heedfull** [comment]
Looks like you don't need any switches anymore `compass install singularitygs` worked for me.

**Comment by scottkellum** [comment]
Cool, glad that got simplified, thanks!
