### ISSUE TITLE
Can't load singularitygs in MAMP project.

### ISSUE THREAD

**Issue by duncanmalashock** [at-import/Singularity#85]
I'm running MAMP on OS 10.8.2, and after running the following on the command line:

sudo gem install singularitygs
sudo gem update
cd /Applications/MAMP/htdocs
compass create trello
cd trello
compass watch

And including 
@import "singularitygs";
in screen.scss, and
require 'singularitygs'
in config.rb

My html file with CSS includes comes up with the following error:
"Syntax error: File to import not found or unreadable: singularitygs. Load paths: /Applications/MAMP/htdocs/trello/sass /Library/Ruby/Gems/1.8/gems/compass-0.12.2/frameworks/blueprint/stylesheets /Library/Ruby/Gems/1.8/gems/compass-0.12.2/frameworks/compass/stylesheets Compass::SpriteImporter on line 7 of /Applications/MAMP/htdocs/trello/sass/screen.scss/screen.scss"

It seems like I should also mention that I ran into a lot of the following warnings during my gem installs:
"/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rdoc/rdoc.rb:280: warning: conflicting chdir during another chdir block
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rdoc/rdoc.rb:287: warning: conflicting chdir during another chdir block
Installing ri documentation for modular-scale-1.0.6
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rdoc/rdoc.rb:280: warning: conflicting chdir during another chdir block
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rdoc/rdoc.rb:287: warning: conflicting chdir during another chdir block"

**Comment by Snugug** [comment]
Why did you create two Compass projects called Trello, seemingly inside each other?

**Comment by duncanmalashock** [comment]
There's only one. I copied that command twice into the text file by mistake.

**Comment by Snugug** [comment]
So to be clear, this is what you've done, in this precise order.

``` bash
sudo gem install singularitygs
sudo gem update
cd /Applications/MAMP/htdocs
compass create trello
cd trello

Open config.rb, add require 'singularitygs'
Add @import "singularitygs" in screen.scss

compass watch
```

**Comment by duncanmalashock** [comment]
That's right. I also restarted MAMP to see whether that would change anything. It didn't.

**Comment by Snugug** [comment]
Can you do `gem list singularitygs` and see if Singularity is installed. Can you also post your `config.rb` file?

**Comment by duncanmalashock** [comment]
```
*** LOCAL GEMS ***

breakpoint (1.3)
chunky_png (1.2.7)
classifier (1.3.3)
compass (0.12.2)
directory_watcher (1.5.1, 1.4.1)
fast-stemmer (1.0.2, 1.0.1)
fssm (0.2.10)
jekyll (0.12.1, 0.12.0)
kramdown (0.14.2, 0.13.8)
liquid (2.5.0, 2.4.1)
maruku (0.6.1)
modular-scale (1.0.6)
posix-spawn (0.3.6)
pygments.rb (0.4.2, 0.3.7)
rubygems-update (2.0.3, 1.8.24)
sass (3.2.7, 3.2.3)
sassy-math (1.5)
singularitygs (0.0.17)
susy (1.0.8, 1.0.5)
syntax (1.0.0)
yajl-ruby (1.1.0)
```

---

config.rb:

```
# Require any additional compass plugins here.
require 'singularitygs'

# Set this to the root of your project when deployed:
http_path = "/"
css_dir = "stylesheets"
sass_dir = "sass"
images_dir = "images"
javascripts_dir = "javascripts"

# You can select your preferred output style here (can be overridden via the command line):
# output_style = :expanded or :nested or :compact or :compressed

# To enable relative paths to assets via compass helper functions. Uncomment:
# relative_assets = true

# To disable debugging comments that display the original location of your selectors. Uncomment:
# line_comments = false


# If you prefer the indented syntax, you might want to regenerate this
# project again passing --syntax sass, or you can uncomment this:
# preferred_syntax = :sass
# and then run:
# sass-convert -R --from scss --to sass sass scss && rm -rf sass && mv scss sass
```

**Comment by scottkellum** [comment]
Please upgrade Singularity to a 1.0 release. You have 0.0.17 and the current version is 1.0.4

**Comment by Snugug** [comment]
You've gotta start using code blocks my friend! Take a look at the "GitHub Flavored Markdown" link.

First step is to upgrade Singularity 1.0. I'm also curious about what your Ruby version is (`ruby -v`). I've never seen the error you encountered, ut it's possible that that has contributed to your issue.

**Comment by scottkellum** [comment]
@duncanmalashock Any luck with this?

**Comment by duncanmalashock** [comment]
@scottkellum Worked like a charm. Thanks to all of you for building a great system!

**Comment by KevinColemanInc** [comment]
I just want to add that I had to assist a lady with an odd error she was getting when trying to save her scss files.  The error was similar to the one mentioned in this thread.

For future people's benefit her problem ended up being Coda's SASS plugin attempting to compile the scss file before it would save.  If you are using Coda, disable any and all SASS plugins before trying to us this tool, because the plugins don't support loading resources from gem files.
