### ISSUE TITLE
`Line 40 of _columns.scss: Undefined operation: "15114-14/976 times 100%"` when using a multi-item $gutters

### ISSUE THREAD

**Issue by lolmaus** [at-import/Singularity#87]
This code produces the error in the topic.

Trace points at the `grid-span` call.

``` sass
// Breakpoints
$s:  400px
$m:  600px
$l:  800px
$xl: 1010px

// Grids
$grids: 1
$grids: add-grid(2 at $s)
$grids: add-grid(3 at $m)
$grids: add-grid(151 151 151 151 151 151 at $xl)

// Gutters
$gutters: 0.2
$gutters: add-gutter(14 at $xl)

#featured
  .element

    +respond-to('m')
      @for $i from 1 through 3
        &:nth-child(#{$i})
          +grid-span(1,$i)

    +respond-to('xl')
      @for $i from 1 through 6
        &:nth-child(#{$i})
          +grid-span(1,$i) // Error trace points at this line
```

To work this issue around i had to redefine `$gutters` without a breakpoint, inside the `respond-to` call:

``` sass
$gutters: 0.2

#featured
  .element

    +respond-to('m')
      @for $i from 1 through 3
        &:nth-child(#{$i})
          +grid-span(1,$i)

    +respond-to('xl')
      $gutters: 14 // Now it works
      @for $i from 1 through 6
        &:nth-child(#{$i})
          +grid-span(1,$i)
```

**Comment by scottkellum** [comment]
Thanks for reporting. To provide a little more context on _why_ this is happening. `$span-and-gutters` is a string and `$gutter` is a list. Together they output `15114-14` and the problem snowballs from there.

Not sure how to fix with straight Sass, but we can force these to numbers using Ruby.

**Comment by Snugug** [comment]
[This has been fixed](https://github.com/Team-Sass/Singularity/commit/a8a9b6a6e5a894d6b275093baaa20555ba7a5650). It's amazing what you overlook when rocking towards a release. Updated gem coming soon.
