### ISSUE TITLE
Float style: second column lacks margins

### ISSUE THREAD

**Issue by lolmaus** [at-import/Singularity#88]
I'm trying to create a thumbnail grid with Singularity 1.x. Here's the code:

``` sass
$cols:    3
$grids:   $cols
$gutters: 0.2

.element
  @for $i from 1 through $cols
    &:nth-child(#{$cols}n+#{$i})
      +grid-span(1,$i, $output-style: 'float')
```

The problem is that the second element (the one that receives grid-span(1,2)) lacks gutter (margin-right).

Screenshots:
- http://d.pr/i/Xsb7+
- http://d.pr/i/ZcMg+

I tried changing the number of columns $cols, and the result is the same: all elements receive correct margin, except for the second one.

How do make second element have correct margin just like the others?

Same issue on StackOverflow:

http://stackoverflow.com/questions/15837452/creating-a-thumbnail-grid-with-singularty-1-x-second-column-lacks-margins

**Comment by scottkellum** [comment]
Looks like this is a bug and float is being applied to the wrong side. I might be able to dig in later today.

**Comment by Snugug** [comment]
This has been found and fixed. Update will be released soon.
