### ISSUE TITLE
Use CSS grid layout syntax

### ISSUE THREAD

**Issue by scottkellum** [at-import/Singularity#9]
CSS grid layout is going to nullify most grid frameworks in the coming years. Might as well start honoring the syntax here.

Reference: http://dev.w3.org/csswg/css3-grid-layout/#repeating-columns-and-rows

Could potentially almost polyfil most functionality using `display: table-cell` but that will be incredibly difficult and problematic.

**Comment by codingdesigner** [comment]
this is beautiful. jump on that.

**Comment by scottkellum** [comment]
The naming of columns is a really cool idea and the repeat function is something that could be used in more than just grid logic. Not sure about the rest of it. Reading through the detail I have semantics I am a little happier with than this as well as a place for padding and fixed gutters.

Would like to implement some of the location stuff but that is going to be impossible without some strict rules on how to structure the HTML.

Semantics issues involve the way Singularity separates the idea of grid columns and grid gutters to be calculated individually. This dramatically simplifies the logic for asymmetrical columns and makes things clearer. So defining gutters within the grid-columns declaration would be annoying.

**Comment by scottkellum** [comment]
Just using the repeat function, and that is done.
